In [1]:
from pathlib import Path
print(Path("./").resolve())

import os
import importlib
from pydantic import AwareDatetime, BaseModel
from typing import *
from enum import StrEnum
from zoneinfo import ZoneInfo
from datetime import datetime, timedelta, timezone, date
from pathlib import Path
from tqdm import tqdm
from itertools import chain, islice
from collections import defaultdict
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd
import yaml
import json
import requests
import pickle
import configparser
import nsapi

C:\Users\jeffw\Code\IDEA\dutch_railways_server\database\src\scraping

In [3]:
working_dir = "./"

In [4]:
out_dir = Path(working_dir) / 'ns_results'
raw_out_dir = out_dir / 'raw'
out_dir.mkdir(parents=True, exist_ok=True)
raw_out_dir.mkdir(parents=True, exist_ok=True)

In [5]:
NS_PRIMARY_KEY = os.environ["NS_PRIMARY_KEY"]
NS_SECONDARY_KEY = os.environ["NS_SECONDARY_KEY"]

NS_GET_HEADER = {
    'Ocp-Apim-Subscription-Key': NS_PRIMARY_KEY,
}

# https://apiportal.ns.nl/apis
NSAPI_URLS = {}
with open('./nsapi/_nsapp-stations-api.yaml') as file:
    NSAPI_URLS['STATIONS']       = yaml.full_load(file)['servers'][0]['url']
with open('./nsapi/_reisinformatie-api.yaml') as file:
    NSAPI_URLS['REISINFORMATIE'] = yaml.full_load(file)['servers'][0]['url']
with open('./nsapi/_virtual-train-API.yaml') as file:
    NSAPI_URLS['VIRTUAL_TRAIN']  = yaml.full_load(file)['servers'][0]['url']

In [6]:
# below not useful (only works with API at foreign station departures)
# FOR_DATE: AwareDatetime = datetime(year=2026, month=6, day=1, tzinfo=ZoneInfo('Europe/Amsterdam'))

## Get train trips

In [7]:
# VEHICLE '/vehicle' https://apiportal.ns.nl/api-details#api=virtual-train-API&operation=getVehicles
# treinen[].ritId (string)
# treinen[].richting (float)
# treinen[].type (string)

In [6]:
vehicles_pkl = raw_out_dir / 'vehicle.pkl'
if not vehicles_pkl.exists():
    response = requests.get(NSAPI_URLS['VIRTUAL_TRAIN'] + '/vehicle', headers=NS_GET_HEADER,
        params=nsapi.virtual_train.ApiVehicleGetParameters(
            lat=52.366667, long=4.883333,
            radius=300000,
            # limit=None,
            # route=route_number,
            # features=materieel_value,
        )
    )
    print('Response:', response.json())
    obj = nsapi.virtual_train.Treinen(**response.json()['payload'])
    with open(vehicles_pkl, 'wb') as file:
        pickle.dump(obj, file, protocol=-1)
else:
    with open(vehicles_pkl, 'rb') as file:
        obj = pickle.load(file)

In [7]:
_trains_raw = {
    x.ritId : x.type
    for x in obj.treinen
}
_service_types = Counter(_trains_raw.values())
TrainServiceType = StrEnum('TrainServiceType', ((x.upper(), x) for x in _service_types))

trains_type_by_id: dict[int, TrainServiceType] = {
    int(k) : TrainServiceType(v)
    for k, v in _trains_raw.items()
}

_sorted_ids = sorted(trains_type_by_id.keys())
print(_service_types)
print(f"{ len(_sorted_ids) }: { min(_sorted_ids) } - { max(_sorted_ids) }")

Counter({'IC': 122, 'SPR': 101})
223: 579 - 704382

## Get trip timetables

In [10]:
# JOURNEY DETAILS '/v2/journey' https://apiportal.ns.nl/api-details#api=reisinformatie-api&operation=getJourneyDetail
# payload.productNumbers (string[])
# payload.plannedStock.trainParts[].stockIdentifier (string) # each trainPart has its own destination (see stop)
# payload.plannedStock.trainType (string)
# payload.stops[].stop.UICCode (string)
# payload.stops[].stop.namen.kort/lang/middel (string)
# payload.stops[].arrivals/departures.product.displayName/operatorName

### For single trip

In [8]:
sample_train_id = 9571 #trains_type_by_id.keys().__iter__().__next__()

response = requests.get(NSAPI_URLS['REISINFORMATIE'] + '/api/v2' + '/journey', headers=NS_GET_HEADER,
    params=nsapi.reisinformatie.ApiV2JourneyGetParameters(
        train=sample_train_id, # required when not giving a journey ID
        # dateTime=FOR_DATE, # date only
        omitCrowdForecast=True,
    )
)
obj = nsapi.reisinformatie.RepresentationResponseJourney(**response.json())

class Stop(BaseModel):
    station_uic: int
    name: str
    arrives: AwareDatetime | None
    departs: AwareDatetime | None
class _TrainService0(BaseModel):
    ritnummer: int
    stops: list[Stop]
    categoryCode: str
    categoryName: str
    trainType: str | None
    trainPart_facilities: dict[int, list[str]] | None

def product_from_stops(stops: list[nsapi.reisinformatie.JourneyStop]) -> nsapi.reisinformatie.ProductInterface:
    for stop in stops:
        if stop.departures:
            return stop.departures[0].product
        if stop.arrivals:
            return stop.arrivals[0].product
    raise Exception()

def stock_from_stops(stops: list[nsapi.reisinformatie.JourneyStop]) -> nsapi.reisinformatie.Stock:
    for stop in stops:
        if stop.plannedStock:
            return stop.plannedStock
    return None

def extract_journey_data(ritnummer: int, obj: nsapi.reisinformatie.RepresentationResponseJourney):
    obj.payload.stops = [x for x in obj.payload.stops if x.status != "PASSING"]

    # assert (len(set(int(x) for x in obj.payload.productNumbers)) == 1) # not true
    assert str(ritnummer) in obj.payload.productNumbers

    for stop in obj.payload.stops:
        if len(stop.arrivals) > 1 or len(stop.departures) > 1:
            raise Exception('a')
        is_first_stop: bool = not stop.previousStopId
        is_last_stop: bool = not stop.nextStopId
        if not(is_first_stop or len(stop.arrivals) > 0):
            # raise Exception(f'Ensure requested train timetable is not for a train that has already departed. prevStopId: {stop.previousStopId}')
            pass # we cannot change this circumstance
        # assert (is_last_stop or len(stop.departures) > 0), stop.nextStopId

        for arr_or_depart in chain(stop.arrivals, stop.departures):
            assert(arr_or_depart.plannedTime.utcoffset() == timedelta(hours=2)) # 1 if DST not in effect

    return _TrainService0(
        ritnummer= ritnummer,
        stops= (Stop(
            station_uic = int(x.stop.uicCode),
            name= x.stop.name,
            arrives= x.arrivals[0].plannedTime if x.arrivals else None,
            departs= x.departures[0].plannedTime if x.departures else None,
        )   for x in obj.payload.stops),
        categoryCode= product_from_stops(obj.payload.stops).categoryCode,
        categoryName= product_from_stops(obj.payload.stops).longCategoryName,
        trainType= stock_from_stops(obj.payload.stops).trainType if stock_from_stops(obj.payload.stops) else None,
        trainPart_facilities= {
            int(y.stockIdentifier): y.facilities
            for y in stock_from_stops(obj.payload.stops).trainParts
        }   if stock_from_stops(obj.payload.stops) else None,
    )

sample_train_timetable = extract_journey_data(sample_train_id, obj)
sample_train_timetable

_TrainService0(ritnummer=9571, stops=[Stop(station_uic=8814001, name='Brussel-Zuid', arrives=None, departs=None), Stop(station_uic=8813003, name='Brussel-Centraal', arrives=None, departs=None), Stop(station_uic=8812005, name='Brussel-Noord', arrives=None, departs=None), Stop(station_uic=8822004, name='Mechelen', arrives=None, departs=None), Stop(station_uic=8821121, name='Antwerpen-Berchem', arrives=None, departs=None), Stop(station_uic=8821006, name='Antwerpen-Centraal', arrives=None, departs=None), Stop(station_uic=8821063, name='Antwerpen-Luchtbal', arrives=None, departs=None), Stop(station_uic=8821105, name='Noorderkempen', arrives=None, departs=None), Stop(station_uic=8400542, name='Rotterdam Lombardijen', arrives=None, departs=None), Stop(station_uic=8400534, name='Rotterdam Stadion', arrives=None, departs=None), Stop(station_uic=8400533, name='Rotterdam Zuid', arrives=None, departs=None), Stop(station_uic=8400529, name='Rotterdam Blaak', arrives=None, departs=None), Stop(station_uic=8400530, name='Rotterdam Centraal', arrives=datetime.datetime(2026, 8, 11, 20, 19, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 11, 20, 21, tzinfo=TzInfo(7200))), Stop(station_uic=8400332, name='Hoofddorp', arrives=None, departs=None), Stop(station_uic=8400561, name='Schiphol Airport', arrives=datetime.datetime(2026, 8, 11, 20, 47, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 11, 20, 49, tzinfo=TzInfo(7200))), Stop(station_uic=8400061, name='Amsterdam Zuid', arrives=datetime.datetime(2026, 8, 11, 20, 55, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 11, 20, 57, tzinfo=TzInfo(7200))), Stop(station_uic=8400056, name='Amsterdam RAI', arrives=None, departs=None), Stop(station_uic=8400194, name='Duivendrecht', arrives=None, departs=None), Stop(station_uic=8400163, name='Diemen Zuid', arrives=None, departs=None)], categoryCode='ECD', categoryName='Eurocity Direct', trainType=None, trainPart_facilities=None)

### For all known train trips

In [9]:
journeys_raw_pkl = raw_out_dir / 'journey_details_raw.pkl'
journeys_pkl = raw_out_dir / 'journey_details.pkl'

def _journey_api_request(train_id: int) -> dict[str, Any]:
    response = requests.get(NSAPI_URLS['REISINFORMATIE'] + '/api/v2' + '/journey', headers=NS_GET_HEADER,
        params=nsapi.reisinformatie.ApiV2JourneyGetParameters(
            train=train_id, # required when not giving a journey ID
            omitCrowdForecast=True,
        )
    )
    return response.json()
def _get_journey_raw_obj() -> dict[str, dict[str, Any]]:
    if not journeys_raw_pkl.exists():
        train_ids = trains_type_by_id.keys()
        raw_obj = {
            train_id : _journey_api_request(train_id)
            for train_id in tqdm(train_ids)
        }
        with open(journeys_raw_pkl, 'wb') as file:
            pickle.dump(raw_obj, file, protocol=-1)
    else:
        with open(journeys_raw_pkl, 'rb') as file:
            raw_obj = pickle.load(file)
    return raw_obj
def _get_journey_obj() -> dict[int, nsapi.reisinformatie.RepresentationResponseJourney]:
    '''May not contain all requested train_ids; some will not be found.'''
    if not journeys_pkl.exists():
        raw_obj = _get_journey_raw_obj()
        obj = dict[int, nsapi.reisinformatie.RepresentationResponseJourney]()
        for k, v in raw_obj.items():
            if (v.get('code', 200) == 404):
                continue
            obj |= {
                k : nsapi.reisinformatie.RepresentationResponseJourney(**v)
            }

        with open(journeys_pkl, 'wb') as file:
            pickle.dump(obj, file, protocol=-1)
    else:
        with open(journeys_pkl, 'rb') as file:
            obj = pickle.load(file)
    return obj

obj = _get_journey_obj()

_trains_timetables: dict[int, _TrainService0] = {
    train_id : extract_journey_data(train_id, journey_obj)
    for train_id, journey_obj in obj.items()
}

_trains_timetables

{6682: _TrainService0(ritnummer=6682, stops=[Stop(station_uic=8400180, name='Dordrecht', arrives=None, departs=datetime.datetime(2026, 8, 10, 22, 28, tzinfo=TzInfo(7200))), Stop(station_uic=8400181, name='Dordrecht Zuid', arrives=datetime.datetime(2026, 8, 10, 22, 31, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 31, tzinfo=TzInfo(7200))), Stop(station_uic=8400382, name='Lage Zwaluwe', arrives=datetime.datetime(2026, 8, 10, 22, 39, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 40, tzinfo=TzInfo(7200))), Stop(station_uic=8400132, name='Breda-Prinsenbeek', arrives=datetime.datetime(2026, 8, 10, 22, 47, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 47, tzinfo=TzInfo(7200))), Stop(station_uic=8400131, name='Breda', arrives=datetime.datetime(2026, 8, 10, 22, 52, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 54, tzinfo=TzInfo(7200))), Stop(station_uic=8400251, name='Gilze-Rijen', arrives=datetime.datetime(2026, 8, 10, 23, 2, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 2, tzinfo=TzInfo(7200))), Stop(station_uic=8400598, name='Tilburg Reeshof', arrives=datetime.datetime(2026, 8, 10, 23, 6, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 6, tzinfo=TzInfo(7200))), Stop(station_uic=8400594, name='Tilburg Universiteit', arrives=datetime.datetime(2026, 8, 10, 23, 10, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 10, tzinfo=TzInfo(7200))), Stop(station_uic=8400597, name='Tilburg', arrives=datetime.datetime(2026, 8, 10, 23, 13, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 14, tzinfo=TzInfo(7200))), Stop(station_uic=8400319, name="'s-Hertogenbosch", arrives=datetime.datetime(2026, 8, 10, 23, 30, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 32, tzinfo=TzInfo(7200))), Stop(station_uic=8400320, name="'s-Hertogenbosch Oost", arrives=datetime.datetime(2026, 8, 10, 23, 35, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 35, tzinfo=TzInfo(7200))), Stop(station_uic=8400524, name='Rosmalen', arrives=datetime.datetime(2026, 8, 10, 23, 39, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 39, tzinfo=TzInfo(7200))), Stop(station_uic=8400496, name='Oss West', arrives=datetime.datetime(2026, 8, 10, 23, 46, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 46, tzinfo=TzInfo(7200))), Stop(station_uic=8400495, name='Oss', arrives=datetime.datetime(2026, 8, 10, 23, 49, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 49, tzinfo=TzInfo(7200))), Stop(station_uic=8400515, name='Ravenstein', arrives=datetime.datetime(2026, 8, 10, 23, 55, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 55, tzinfo=TzInfo(7200))), Stop(station_uic=8400710, name='Wijchen', arrives=datetime.datetime(2026, 8, 11, 0, 1, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 11, 0, 1, tzinfo=TzInfo(7200))), Stop(station_uic=8400475, name='Nijmegen Dukenburg', arrives=datetime.datetime(2026, 8, 11, 0, 5, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 11, 0, 5, tzinfo=TzInfo(7200))), Stop(station_uic=8400477, name='Nijmegen Goffert', arrives=datetime.datetime(2026, 8, 11, 0, 8, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 11, 0, 8, tzinfo=TzInfo(7200))), Stop(station_uic=8400470, name='Nijmegen', arrives=datetime.datetime(2026, 8, 11, 0, 13, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2201: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 6481: _TrainService0(ritnummer=6481, stops=[Stop(station_uic=8400594, name='Tilburg Universiteit', arrives=None, departs=datetime.datetime(2026, 8, 10, 22, 34, tzinfo=TzInfo(7200))), Stop(station_uic=8400597, name='Tilburg', arrives=datetime.datetime(2026, 8, 10, 22, 38, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 39, tzinfo=TzInfo(7200))), Stop(station_uic=8400482, name='Oisterwijk', arrives=datetime.datetime(2026, 8, 10, 22, 45, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 45, tzinfo=TzInfo(7200))), Stop(station_uic=8400129, name='Boxtel', arrives=datetime.datetime(2026, 8, 10, 22, 52, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 53, tzinfo=TzInfo(7200))), Stop(station_uic=8400112, name='Best', arrives=datetime.datetime(2026, 8, 10, 22, 59, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 59, tzinfo=TzInfo(7200))), Stop(station_uic=8400196, name='Eindhoven Strijp-S', arrives=datetime.datetime(2026, 8, 10, 23, 5, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 5, tzinfo=TzInfo(7200))), Stop(station_uic=8400206, name='Eindhoven Centraal', arrives=datetime.datetime(2026, 8, 10, 23, 9, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 17, tzinfo=TzInfo(7200))), Stop(station_uic=8400245, name='Geldrop', arrives=datetime.datetime(2026, 8, 10, 23, 22, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 22, tzinfo=TzInfo(7200))), Stop(station_uic=8400308, name='Heeze', arrives=datetime.datetime(2026, 8, 10, 23, 26, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 26, tzinfo=TzInfo(7200))), Stop(station_uic=8400432, name='Maarheeze', arrives=datetime.datetime(2026, 8, 10, 23, 33, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 33, tzinfo=TzInfo(7200))), Stop(station_uic=8400684, name='Weert', arrives=datetime.datetime(2026, 8, 10, 23, 40, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2202: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 6582: _TrainService0(ritnummer=6582, stops=[Stop(station_uic=8400206, name='Eindhoven Centraal', arrives=None, departs=datetime.datetime(2026, 8, 10, 22, 35, tzinfo=TzInfo(7200))), Stop(station_uic=8400196, name='Eindhoven Strijp-S', arrives=datetime.datetime(2026, 8, 10, 22, 39, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 39, tzinfo=TzInfo(7200))), Stop(station_uic=8400112, name='Best', arrives=datetime.datetime(2026, 8, 10, 22, 44, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 44, tzinfo=TzInfo(7200))), Stop(station_uic=8400129, name='Boxtel', arrives=datetime.datetime(2026, 8, 10, 22, 51, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 51, tzinfo=TzInfo(7200))), Stop(station_uic=8400667, name='Vught', arrives=datetime.datetime(2026, 8, 10, 22, 58, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 58, tzinfo=TzInfo(7200))), Stop(station_uic=8400319, name="'s-Hertogenbosch", arrives=datetime.datetime(2026, 8, 10, 23, 3, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2203: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 6581: _TrainService0(ritnummer=6581, stops=[Stop(station_uic=8400319, name="'s-Hertogenbosch", arrives=None, departs=datetime.datetime(2026, 8, 10, 22, 28, tzinfo=TzInfo(7200))), Stop(station_uic=8400667, name='Vught', arrives=datetime.datetime(2026, 8, 10, 22, 32, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 32, tzinfo=TzInfo(7200))), Stop(station_uic=8400129, name='Boxtel', arrives=datetime.datetime(2026, 8, 10, 22, 39, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 39, tzinfo=TzInfo(7200))), Stop(station_uic=8400112, name='Best', arrives=datetime.datetime(2026, 8, 10, 22, 45, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 45, tzinfo=TzInfo(7200))), Stop(station_uic=8400196, name='Eindhoven Strijp-S', arrives=datetime.datetime(2026, 8, 10, 22, 51, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 51, tzinfo=TzInfo(7200))), Stop(station_uic=8400206, name='Eindhoven Centraal', arrives=datetime.datetime(2026, 8, 10, 22, 55, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 6, tzinfo=TzInfo(7200))), Stop(station_uic=8400242, name='Helmond Brandevoort', arrives=datetime.datetime(2026, 8, 10, 23, 12, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 12, tzinfo=TzInfo(7200))), Stop(station_uic=8400300, name="Helmond 't Hout", arrives=datetime.datetime(2026, 8, 10, 23, 15, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 15, tzinfo=TzInfo(7200))), Stop(station_uic=8400313, name='Helmond', arrives=datetime.datetime(2026, 8, 10, 23, 19, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 19, tzinfo=TzInfo(7200))), Stop(station_uic=8400299, name='Helmond Brouwhuis', arrives=datetime.datetime(2026, 8, 10, 23, 22, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 22, tzinfo=TzInfo(7200))), Stop(station_uic=8400172, name='Deurne', arrives=datetime.datetime(2026, 8, 10, 23, 27, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2212: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI'], 2208: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 6683: _TrainService0(ritnummer=6683, stops=[Stop(station_uic=8400470, name='Nijmegen', arrives=None, departs=datetime.datetime(2026, 8, 10, 22, 20, tzinfo=TzInfo(7200))), Stop(station_uic=8400477, name='Nijmegen Goffert', arrives=datetime.datetime(2026, 8, 10, 22, 23, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 23, tzinfo=TzInfo(7200))), Stop(station_uic=8400475, name='Nijmegen Dukenburg', arrives=datetime.datetime(2026, 8, 10, 22, 26, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 26, tzinfo=TzInfo(7200))), Stop(station_uic=8400710, name='Wijchen', arrives=datetime.datetime(2026, 8, 10, 22, 31, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 31, tzinfo=TzInfo(7200))), Stop(station_uic=8400515, name='Ravenstein', arrives=datetime.datetime(2026, 8, 10, 22, 36, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 36, tzinfo=TzInfo(7200))), Stop(station_uic=8400495, name='Oss', arrives=datetime.datetime(2026, 8, 10, 22, 42, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 43, tzinfo=TzInfo(7200))), Stop(station_uic=8400496, name='Oss West', arrives=datetime.datetime(2026, 8, 10, 22, 46, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 46, tzinfo=TzInfo(7200))), Stop(station_uic=8400524, name='Rosmalen', arrives=datetime.datetime(2026, 8, 10, 22, 53, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 53, tzinfo=TzInfo(7200))), Stop(station_uic=8400320, name="'s-Hertogenbosch Oost", arrives=datetime.datetime(2026, 8, 10, 22, 57, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 57, tzinfo=TzInfo(7200))), Stop(station_uic=8400319, name="'s-Hertogenbosch", arrives=datetime.datetime(2026, 8, 10, 23, 0, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 2, tzinfo=TzInfo(7200))), Stop(station_uic=8400597, name='Tilburg', arrives=datetime.datetime(2026, 8, 10, 23, 16, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 18, tzinfo=TzInfo(7200))), Stop(station_uic=8400594, name='Tilburg Universiteit', arrives=datetime.datetime(2026, 8, 10, 23, 21, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 21, tzinfo=TzInfo(7200))), Stop(station_uic=8400598, name='Tilburg Reeshof', arrives=datetime.datetime(2026, 8, 10, 23, 25, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 25, tzinfo=TzInfo(7200))), Stop(station_uic=8400251, name='Gilze-Rijen', arrives=datetime.datetime(2026, 8, 10, 23, 29, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 29, tzinfo=TzInfo(7200))), Stop(station_uic=8400131, name='Breda', arrives=datetime.datetime(2026, 8, 10, 23, 36, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 39, tzinfo=TzInfo(7200))), Stop(station_uic=8400132, name='Breda-Prinsenbeek', arrives=datetime.datetime(2026, 8, 10, 23, 43, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 43, tzinfo=TzInfo(7200))), Stop(station_uic=8400382, name='Lage Zwaluwe', arrives=datetime.datetime(2026, 8, 10, 23, 50, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 50, tzinfo=TzInfo(7200))), Stop(station_uic=8400181, name='Dordrecht Zuid', arrives=datetime.datetime(2026, 8, 10, 23, 58, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 58, tzinfo=TzInfo(7200))), Stop(station_uic=8400180, name='Dordrecht', arrives=datetime.datetime(2026, 8, 11, 0, 2, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2222: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 6488: _TrainService0(ritnummer=6488, stops=[Stop(station_uic=8400684, name='Weert', arrives=None, departs=datetime.datetime(2026, 8, 10, 22, 50, tzinfo=TzInfo(7200))), Stop(station_uic=8400432, name='Maarheeze', arrives=datetime.datetime(2026, 8, 10, 22, 56, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 56, tzinfo=TzInfo(7200))), Stop(station_uic=8400308, name='Heeze', arrives=datetime.datetime(2026, 8, 10, 23, 3, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 3, tzinfo=TzInfo(7200))), Stop(station_uic=8400245, name='Geldrop', arrives=datetime.datetime(2026, 8, 10, 23, 7, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 7, tzinfo=TzInfo(7200))), Stop(station_uic=8400206, name='Eindhoven Centraal', arrives=datetime.datetime(2026, 8, 10, 23, 13, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2230: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 5175: _TrainService0(ritnummer=5175, stops=[Stop(station_uic=8400282, name='Den Haag Centraal', arrives=None, departs=datetime.datetime(2026, 8, 10, 22, 26, tzinfo=TzInfo(7200))), Stop(station_uic=8400280, name='Den Haag HS', arrives=datetime.datetime(2026, 8, 10, 22, 29, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 30, tzinfo=TzInfo(7200))), Stop(station_uic=8400279, name='Den Haag Moerwijk', arrives=datetime.datetime(2026, 8, 10, 22, 33, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 33, tzinfo=TzInfo(7200))), Stop(station_uic=8400505, name='Rijswijk', arrives=datetime.datetime(2026, 8, 10, 22, 36, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 36, tzinfo=TzInfo(7200))), Stop(station_uic=8400170, name='Delft', arrives=datetime.datetime(2026, 8, 10, 22, 40, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 40, tzinfo=TzInfo(7200))), Stop(station_uic=8400166, name='Delft Campus', arrives=datetime.datetime(2026, 8, 10, 22, 43, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 43, tzinfo=TzInfo(7200))), Stop(station_uic=8400553, name='Schiedam Centrum', arrives=datetime.datetime(2026, 8, 10, 22, 50, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 50, tzinfo=TzInfo(7200))), Stop(station_uic=8400530, name='Rotterdam Centraal', arrives=datetime.datetime(2026, 8, 10, 22, 54, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 56, tzinfo=TzInfo(7200))), Stop(station_uic=8400529, name='Rotterdam Blaak', arrives=datetime.datetime(2026, 8, 10, 22, 59, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 59, tzinfo=TzInfo(7200))), Stop(station_uic=8400533, name='Rotterdam Zuid', arrives=datetime.datetime(2026, 8, 10, 23, 2, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 2, tzinfo=TzInfo(7200))), Stop(station_uic=8400534, name='Rotterdam Stadion', arrives=None, departs=None), Stop(station_uic=8400542, name='Rotterdam Lombardijen', arrives=datetime.datetime(2026, 8, 10, 23, 6, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 6, tzinfo=TzInfo(7200))), Stop(station_uic=8400090, name='Barendrecht', arrives=datetime.datetime(2026, 8, 10, 23, 9, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 9, tzinfo=TzInfo(7200))), Stop(station_uic=8400752, name='Zwijndrecht', arrives=datetime.datetime(2026, 8, 10, 23, 15, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 15, tzinfo=TzInfo(7200))), Stop(station_uic=8400180, name='Dordrecht', arrives=datetime.datetime(2026, 8, 10, 23, 19, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='SNG', trainPart_facilities={2301: ['FIETS', 'WIFI', 'STROOM', 'TOEGANKELIJK', 'TOILET'], 2722: ['FIETS', 'WIFI', 'STROOM', 'TOEGANKELIJK', 'TOILET']}),
 4178: _TrainService0(ritnummer=4178, stops=[Stop(station_uic=8400332, name='Hoofddorp', arrives=None, departs=datetime.datetime(2026, 8, 10, 22, 38, tzinfo=TzInfo(7200))), Stop(station_uic=8400561, name='Schiphol Airport', arrives=datetime.datetime(2026, 8, 10, 22, 42, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 43, tzinfo=TzInfo(7200))), Stop(station_uic=8400079, name='Amsterdam Lelylaan', arrives=datetime.datetime(2026, 8, 10, 22, 50, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 22, 50, tzinfo=TzInfo(7200))), Stop(station_uic=8400059, name='Amsterdam Sloterdijk', arrives=datetime.datetime(2026, 8, 10, 22, 54, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 3, tzinfo=TzInfo(7200))), Stop(station_uic=8400731, name='Zaandam', arrives=datetime.datetime(2026, 8, 10, 23, 9, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 9, tzinfo=TzInfo(7200))), Stop(station_uic=8400728, name='Zaandam Kogerveld', arrives=datetime.datetime(2026, 8, 10, 23, 14, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 14, tzinfo=TzInfo(7200))), Stop(station_uic=8400499, name='Purmerend Weidevenne', arrives=datetime.datetime(2026, 8, 10, 23, 20, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 20, tzinfo=TzInfo(7200))), Stop(station_uic=8400508, name='Purmerend', arrives=datetime.datetime(2026, 8, 10, 23, 23, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 23, tzinfo=TzInfo(7200))), Stop(station_uic=8400506, name='Purmerend Overwhere', arrives=datetime.datetime(2026, 8, 10, 23, 25, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 25, tzinfo=TzInfo(7200))), Stop(station_uic=8400337, name='Hoorn', arrives=datetime.datetime(2026, 8, 10, 23, 37, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 23, 38, tzinfo=TzInfo(7200))), Stop(station_uic=8400336, name='Hoorn Kersenboogerd', arrives=datetime.datetime(2026, 8, 10, 23, 42, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='SNG', trainPart_facilities={3034: ['FIETS', 'WIFI', 'STROOM', 'TOEGANKELIJK', 'TOILET'], 2315: ['FIETS', 'WIFI', 'STROOM', 'TOEGANKELIJK', 'TOILET']}),

#### Create enums

In [10]:
_category_codes = Counter(x.categoryCode for x in _trains_timetables.values())
CategoryCode = StrEnum('CategoryCode', ((x.upper(), x) for x in _category_codes))
print(_category_codes)

_category_names = Counter(x.categoryName for x in _trains_timetables.values())
CategoryName = StrEnum('CategoryName', ((x.upper(), x) for x in _category_names))
print(_category_names)

_train_types = Counter(x.trainType for x in _trains_timetables.values() if x.trainType)
TrainType = StrEnum('TrainType', ((x.upper(), x) for x in _train_types))
print(_train_types)

_facilities = Counter(
    z
    for x in _trains_timetables.values()
    if x.trainPart_facilities
    for y in x.trainPart_facilities.values()
    for z in y
)
Facility = StrEnum('Facility', ((x.upper(), x) for x in _facilities))
print(_facilities)

Counter({'IC': 110, 'SPR': 101, 'ICD': 9, 'ECD': 3})
Counter({'Intercity': 110, 'Sprinter': 101, 'Intercity direct': 9, 'Eurocity Direct': 3})
Counter({'VIRM': 66, 'SNG': 42, 'SLT': 42, 'DDZ': 20, 'ICNG': 19, 'Flirt': 17, 'ICM': 14})
Counter({'TOILET': 256, 'FIETS': 256, 'WIFI': 198, 'STROOM': 177, 'TOEGANKELIJK': 151, 'STILTE': 126})

#### Apply enums

In [11]:
class TrainService(BaseModel):
    ritnummer: int
    stops: list[Stop]
    categoryCode: CategoryCode
    categoryName: CategoryName
    trainType: TrainType | None
class StockFacility(BaseModel):
    trainType: TrainType
    facilities: list[Facility]

train_timetables = {
    k : TrainService(
        ritnummer= v.ritnummer,
        stops= v.stops,
        categoryCode= CategoryCode(v.categoryCode),
        categoryName= CategoryName(v.categoryName),
        trainType= TrainType(v.trainType) if v.trainType else None,
    )
    for k, v in _trains_timetables.items()
}

_facilities_by_trainType: defaultdict[TrainType, Counter[Facility]] = defaultdict(lambda: Counter[Facility]())
for v in _trains_timetables.values():
    if not(v.trainType) and not(v.trainPart_facilities):
        continue
    _facilities_by_trainType[v.trainType].update(
        Facility(x)
        for facilities in v.trainPart_facilities.values()
        for x in facilities
    )
print(json.dumps(_facilities_by_trainType, indent=4))

facilities_by_trainType: dict[TrainType, list[Facility]] = {
    k : list[Facility](v.keys())
    for k, v in _facilities_by_trainType.items()
}

{
    "Flirt": {
        "TOILET": 18,
        "STROOM": 18,
        "FIETS": 18,
        "TOEGANKELIJK": 18,
        "WIFI": 18
    },
    "SNG": {
        "FIETS": 54,
        "WIFI": 54,
        "STROOM": 54,
        "TOEGANKELIJK": 54,
        "TOILET": 54
    },
    "SLT": {
        "FIETS": 58,
        "TOILET": 58,
        "TOEGANKELIJK": 58
    },
    "ICNG": {
        "WIFI": 21,
        "TOILET": 21,
        "STILTE": 21,
        "STROOM": 21,
        "FIETS": 21,
        "TOEGANKELIJK": 21
    },
    "ICM": {
        "WIFI": 15,
        "TOILET": 15,
        "STILTE": 15,
        "STROOM": 15,
        "FIETS": 15
    },
    "DDZ": {
        "WIFI": 21,
        "TOILET": 21,
        "STILTE": 21,
        "STROOM": 21,
        "FIETS": 21
    },
    "VIRM": {
        "WIFI": 69,
        "TOILET": 69,
        "STILTE": 69,
        "FIETS": 69,
        "STROOM": 48
    }
}

## Get train stations

In [15]:
# STATIONS '/v3' https://apiportal.ns.nl/api-details#api=nsapp-stations-api&operation=getStationsV3
# payload.id.uicCode
# payload.id.code # eg UT for Utrecht Centraal
# payload.stationType (enum)
# payload.names.long/medium/short/festive/synonyms[]
# payload.location.lat/lng (number)

In [14]:
stations_pkl = raw_out_dir / 'stations.pkl'
if not stations_pkl.exists():
    response = requests.get(NSAPI_URLS['STATIONS'] + '/v3', headers=NS_GET_HEADER,
        params=nsapi.nsapp_stations.V3GetParameters(
            countryCodes=['NL'],
            limit=None # irrelevant when not providing str `q`
        )
    )
    obj = nsapi.nsapp_stations.StationsV3Response(**response.json())
    with open(stations_pkl, 'wb') as file:
        pickle.dump(obj, file, protocol=-1)
else:
    with open(stations_pkl, 'rb') as file:
        obj = pickle.load(file)

In [15]:
StationInfo = NamedTuple('StationInfo', (
    ('name', str),
    ('lat', float),
    ('lng', float),
))

stations_by_uicCode: dict[int, StationInfo] = {
    int(x.id.uicCode) : StationInfo(
        name=x.names.long,
        lat=x.location.lat,
        lng=x.location.lng,
    )
    for x in obj.payload
}

_uics = sorted(stations_by_uicCode.keys())
_names_len = sorted(
    (x.name for x in stations_by_uicCode.values()),
    key=len
)
_names_words = sorted(
    (x.name for x in stations_by_uicCode.values()),
    key=lambda s: len(s.split())
)
print(_uics[:1] + ['...'] + _uics[-1:])
print('========')
print(_names_len[:3] + ['...'] + _names_len[-3:])
print('========')
print(_names_words[:3] + ['...'] + _names_words[-3:])

[8400045, '...', 8400752]
========
['Oss', 'Olst', 'Elst', '...', 'Bovenkarspel-Grootebroek', 'Lansingerland-Zoetermeer', 'Leeuwarden Camminghaburen']
========
["'s-Hertogenbosch", 'Alkmaar', 'Almelo', '...', 'Zandvoort aan Zee', 'Koog aan de Zaan', 'Den Haag Laan v NOI']

## Export for SQL

In [18]:
reveal_type(trains_type_by_id)
reveal_type(train_timetables)
reveal_type(facilities_by_trainType)
reveal_type(stations_by_uicCode)

Runtime type is 'dict'
Runtime type is 'dict'
Runtime type is 'dict'
Runtime type is 'dict'

{8400301: StationInfo(name='Heerenveen IJsstadion', lat=52.9352760314941, lng=5.94388866424561),
 8400534: StationInfo(name='Rotterdam Stadion', lat=51.8938903808594, lng=4.51972198486328),
 8400058: StationInfo(name='Amsterdam Centraal', lat=52.3788871765137, lng=4.90027761459351),
 8400282: StationInfo(name='Den Haag Centraal', lat=52.0802764892578, lng=4.32499980926514),
 8400206: StationInfo(name='Eindhoven Centraal', lat=51.4433326721191, lng=5.48138904571533),
 8400530: StationInfo(name='Rotterdam Centraal', lat=51.9249992370605, lng=4.46888875961304),
 8400561: StationInfo(name='Schiphol Airport', lat=52.3094444274902, lng=4.76194429397583),
 8400621: StationInfo(name='Utrecht Centraal', lat=52.0888900756836, lng=5.11027765274048),
 8400319: StationInfo(name="'s-Hertogenbosch", lat=51.69048, lng=5.29362),
 8400050: StationInfo(name='Alkmaar', lat=52.6377792358398, lng=4.73972225189209),
 8400051: StationInfo(name='Almelo', lat=52.3580551147461, lng=6.65388870239258),
 8400080: StationInfo(name='Almere Centrum', lat=52.37503, lng=5.21764),
 8400053: StationInfo(name='Alphen a/d Rijn', lat=52.1244430541992, lng=4.65777778625488),
 8400055: StationInfo(name='Amersfoort Centraal', lat=52.1538887023926, lng=5.37055540084839),
 8400059: StationInfo(name='Amsterdam Sloterdijk', lat=52.3888893127441, lng=4.83777761459351),
 8400066: StationInfo(name='Apeldoorn', lat=52.2091674804687, lng=5.97027778625488),
 8400071: StationInfo(name='Arnhem Centraal', lat=51.9850006103516, lng=5.89916658401489),
 8400073: StationInfo(name='Assen', lat=52.9916648864746, lng=6.57083320617676),
 8400131: StationInfo(name='Breda', lat=51.5955543518066, lng=4.78000020980835),
 8400170: StationInfo(name='Delft', lat=52.0066680908203, lng=4.35638904571533),
 8400280: StationInfo(name='Den Haag HS', lat=52.0697212219238, lng=4.32250022888184),
 8400173: StationInfo(name='Deventer', lat=52.2574996948242, lng=6.16055536270142),
 8400180: StationInfo(name='Dordrecht', lat=51.8072204589844, lng=4.66833353042603),
 8400200: StationInfo(name='Ede-Wageningen', lat=52.0277786254883, lng=5.67305564880371),
 8400212: StationInfo(name='Enschede', lat=52.2224998474121, lng=6.8899998664856),
 8400258: StationInfo(name='Gouda', lat=52.0175018310547, lng=4.70444440841675),
 8400263: StationInfo(name='Groningen', lat=53.2105560302734, lng=6.56472206115723),
 8400285: StationInfo(name='Haarlem', lat=52.3877792358398, lng=4.63833332061768),
 8400307: StationInfo(name='Heerlen', lat=50.8908348083496, lng=5.97499990463257),
 8400313: StationInfo(name='Helmond', lat=51.4755554199219, lng=5.66194438934326),
 8400316: StationInfo(name='Hengelo', lat=52.2616653442383, lng=6.79388904571533),
 8400322: StationInfo(name='Hilversum', lat=52.2258338928223, lng=5.18194437026978),
 8400337: StationInfo(name='Hoorn', lat=52.6447219848633, lng=5.05555534362793),
 8400387: StationInfo(name='Leeuwarden', lat=53.1958351135254, lng=5.79222202301025),
 8400390: StationInfo(name='Leiden Centraal', lat=52.1661109924316, lng=4.48166656494141),
 8400394: StationInfo(name='Lelystad Centrum', lat=52.5077781677246, lng=5.47277784347534),
 8400424: StationInfo(name='Maastricht', lat=50.8502769470215, lng=5.70555543899536),
 8400470: StationInfo(name='Nijmegen', lat=51.8436126708984, lng=5.85222244262695),
 8400495: StationInfo(name='Oss', lat=51.7655563354492, lng=5.53222227096558),
 8400523: StationInfo(name='Roermond', lat=51.1930541992188, lng=5.9941668510437),
 8400526: StationInfo(name='Roosendaal', lat=51.5402793884277, lng=4.45833349227905),
 8400564: StationInfo(name='Sittard', lat=51.0016670227051, lng=5.85861110687256),
 8400597: StationInfo(name='Tilburg', lat=51.5605545043945, lng=5.08361101150513),
 8400644: StationInfo(name='Venlo', lat=51.3636093139648, lng=6.17277765274048),
 8400652: StationInfo(name='Vlissingen', lat=51.4458351135254, lng=3.59527778625488),
 8400731: StationInfo(name='Zaandam', lat=52.4388885498047, lng=4.81361103057861),
 8400744: StationInfo(name='Zutphen', lat=52.1452789306641, lng=6.19416666030884),
 8400747: StationInfo(name='Zwolle', lat=52.5047225952148, lng=6.09194421768188),
 8400057: StationInfo(name='Amsterdam Amstel', lat=52.3466682434082, lng=4.91777801513672),
 8400061: StationInfo(name='Amsterdam Zuid', lat=52.338889, lng=4.872356),
 8400151: StationInfo(name='Castricum', lat=52.5458335876465, lng=4.65861129760742),
 8400311: StationInfo(name='Den Helder', lat=52.9552764892578, lng=4.76111125946045),
 8400176: StationInfo(name='Dieren', lat=52.0449981689453, lng=6.10305547714233),
 8400218: StationInfo(name='Etten-Leur', lat=51.5750007629395, lng=4.63583326339722),
 8400302: StationInfo(name='Heemstede-Aerdenhout', lat=52.3591651916504, lng=4.60666656494141),
 8400305: StationInfo(name='Heerenveen', lat=52.9613876342773, lng=5.91416645050049),
 8400486: StationInfo(name='Olst', lat=52.3347206115723, lng=6.11305570602417),
 8400507: StationInfo(name='Rotterdam Alexander', lat=51.9519462585449, lng=4.55361127853394),
 8400578: StationInfo(name='Steenwijk', lat=52.7915109924316, lng=6.11455576324463),
 8400684: StationInfo(name='Weert', lat=51.2486114501953, lng=5.70361089706421),
 8400711: StationInfo(name='Wijhe', lat=52.3902778625488, lng=6.1405553817749),
 8400139: StationInfo(name='Buitenpost', lat=53.2564547, lng=6.1446496),
 8400153: StationInfo(name='Coevorden', lat=52.6636123657227, lng=6.73555564880371),
 8400428: StationInfo(name='Mariënberg', lat=52.5094451904297, lng=6.57527780532837),
 8400487: StationInfo(name='Ommen', lat=52.5094451904297, lng=6.41583347320557),
 8400632: StationInfo(name='Valkenburg', lat=50.8697204589844, lng=5.83222198486328),
 8400167: StationInfo(name='Dalfsen', lat=52.4983329772949, lng=6.25861120223999),
 8400208: StationInfo(name='Emmen', lat=52.7900009155273, lng=6.89944458007812),
 8400407: StationInfo(name='Emmen Zuid', lat=52.7488663746914, lng=6.87478065490722),
 8400293: StationInfo(name='Hardenberg', lat=52.5727767944336, lng=6.62861108779907),
 8400434: StationInfo(name='Meerssen', lat=50.882879392551, lng=5.75099945068359),
 8400454: StationInfo(name='Nieuw Amsterdam', lat=52.7186126708984, lng=6.84861087799072),
 8400074: StationInfo(name='Amsterdam Bijlmer ArenA', lat=52.3122215270996, lng=4.94694423675537),
 8400086: StationInfo(name='Baarn', lat=52.2083320617676, lng=5.28083324432373),
 8400457: StationInfo(name='Bad Nieuweschans', lat=53.1844, lng=7.19937),
 8400128: StationInfo(name='Boxmeer', lat=51.6445217676531, lng=5.93903303146362),
 8400129: StationInfo(name='Boxtel', lat=51.58433, lng=5.31912),
 8400133: StationInfo(name='Breukelen', lat=52.17149, lng=4.9906),
 8400179: StationInfo(name='Den Dolder', lat=52.1402778625488, lng=5.24277782440186),
 8400380: StationInfo(name='Den Haag Laan v NOI', lat=52.0786094665527, lng=4.34277772903442),
 8400177: StationInfo(name='Doetinchem', lat=51.9585962, lng=6.2962148),
 8400182: StationInfo(name='Driebergen-Zeist', lat=52.0652770996094, lng=5.25861120223999),
 8400194: StationInfo(name='Duivendrecht', lat=52.3233337402344, lng=4.93638896942139),
 8400207: StationInfo(name='Elst', lat=51.9169425964355, lng=5.85500001907349),
 8400244: StationInfo(name='Geldermalsen', lat=51.88301, lng=5.27127),
 8400245: StationInfo(name='Geldrop', lat=51.4197235107422, lng=5.55055570602417),
 8400256: StationInfo(name='Gorinchem', lat=51.8338890075684, lng=4.96833324432373),
 8400294: StationInfo(name='Harderwijk', lat=52.3375015258789, lng=5.61972236633301),
 8400306: StationInfo(name='Heerhugowaard', lat=52.6697235107422, lng=4.82277774810791),
 8400331: StationInfo(name='Hoogezand-Sappemeer', lat=53.1598181316756, lng=6.77075386047363),
 8400340: StationInfo(name='Houten', lat=52.03402, lng=5.16821),
 8400355: StationInfo(name='Kerkrade Centrum', lat=50.8616676330566, lng=6.05749988555908),
 8400382: StationInfo(name='Lage Zwaluwe', lat=51.6911125183105, lng=4.66305541992188),
 8400548: StationInfo(name='Landgraaf', lat=50.8963890075684, lng=6.01916646957398),
 8400417: StationInfo(name='Maarn', lat=52.0641670227051, lng=5.36999988555908),
 8400426: StationInfo(name='Maastricht Randwyck', lat=50.8386116027832, lng=5.71722221374512),
 8400435: StationInfo(name='Meppel', lat=52.6908340454102, lng=6.19750022888184),
 8400452: StationInfo(name='Naarden-Bussum', lat=52.2802772521973, lng=5.15694427490234),
 8400508: StationInfo(name='Purmerend', lat=52.5030555725098, lng=4.95361089706421),
 8400517: StationInfo(name='Rhenen', lat=51.958610534668, lng=5.57833337783814),
 8400566: StationInfo(name='Sneek', lat=53.0328688, lng=5.6523969),
 8400567: StationInfo(name='Soest', lat=52.1733322143555, lng=5.30999994277954),
 8400596: StationInfo(name='Tiel', lat=51.8894462585449, lng=5.42222213745117),
 8400615: StationInfo(name='Uitgeest', lat=52.5216674804687, lng=4.70166683197022),
 8400620: StationInfo(name='Utrecht Overvecht', lat=52.1100006103516, lng=5.12472200393677),
 8400606: StationInfo(name='Utrecht Vaartsche Rijn', lat=52.078889, lng=5.121667),
 8400636: StationInfo(name='Veendam', lat=53.10324, lng=6.88475),
 8400627: StationInfo(name='Veenendaal Centrum', lat=52.0200004577637, lng=5.54861116409302),
 8400646: StationInfo(name='Venray', lat=51.526568099007, lng=6.01417779922485),
 8400685: StationInfo(name='Weesp', lat=52.3127784729004, lng=5.04305553436279),
 8400691: StationInfo(name='Wierden', lat=52.3613891601562, lng=6.59166669845581),
 8400696: StationInfo(name='Winschoten', lat=53.1392377, lng=7.035101),
 8400698: StationInfo(name='Winterswijk', lat=51.9677307, lng=6.7155181),
 8400702: StationInfo(name='Woerden', lat=52.0849990844727, lng=4.89361095428467),
 8400364: StationInfo(name='Zaandijk Zaanse Schans', lat=52.469165802002, lng=4.80499982833862),
 8400735: StationInfo(name='Zevenaar', lat=51.9230537414551, lng=6.07194423675537),
 8400741: StationInfo(name='Zoetermeer', lat=52.0475006103516, lng=4.47722244262695),
 8400742: StationInfo(name='Zuidbroek', lat=53.1596122800056, lng=6.8679141998291),
 8400320: StationInfo(name="'s-Hertogenbosch Oost", lat=51.700553894043, lng=5.3183331489563),
 8400388: StationInfo(name="'t Harde", lat=52.4091682, lng=5.893611),
 8400045: StationInfo(name='Aalten', lat=51.9213265245505, lng=6.57862722873687),
 8400047: StationInfo(name='Abcoude', lat=52.2785, lng=4.977),
 8400049: StationInfo(name='Akkrum', lat=53.0463905334473, lng=5.84361124038696),
 8400052: StationInfo(name='Alkmaar Noord', lat=52.6438903808594, lng=4.76416683197022),
 8400520: StationInfo(name='Almelo de Riet', lat=52.3419456481934, lng=6.66666650772095),
 8400081: StationInfo(name='Almere Buiten', lat=52.3941650390625, lng=5.2780556678772),
 8400082: StationInfo(name='Almere Muziekwijk', lat=52.3675003051758, lng=5.19027757644653),
 8400226: StationInfo(name='Almere Oostvaarders', lat=52.4033317565918, lng=5.30055570602417),
 8400104: StationInfo(name='Almere Parkwijk', lat=52.3766670227051, lng=5.24472236633301),
 8400450: StationInfo(name='Almere Poort', lat=52.342778, lng=5.151944),
 8400054: StationInfo(name='Amersfoort Schothorst', lat=52.1748221374512, lng=5.40388870239258),
 8400228: StationInfo(name='Amersfoort Vathorst', lat=52.1927795410156, lng=5.43388891220093),
 8400231: StationInfo(name='Amsterdam Holendrecht', lat=52.29844, lng=4.95972),
 8400079: StationInfo(name='Amsterdam Lelylaan', lat=52.3577766418457, lng=4.83388900756836),
 8400060: StationInfo(name='Amsterdam Muiderpoort', lat=52.3605537414551, lng=4.93111133575439),
 8400056: StationInfo(name='Amsterdam RAI', lat=52.3372230529785, lng=4.89027786254883),
 8400235: StationInfo(name='Amsterdam Science Park', lat=52.35274, lng=4.94855),
 8400065: StationInfo(name='Anna Paulowna', lat=52.8672218322754, lng=4.81111097335815),
 8400233: StationInfo(name='Apeldoorn De Maten', lat=52.2052764892578, lng=6.00055551528931),
 8400229: StationInfo(name='Apeldoorn Osseveld', lat=52.2152786254883, lng=6.00444459915161),
 8400067: StationInfo(name='Appingedam', lat=53.3258135, lng=6.8619577),
 8400068: StationInfo(name='Arkel', lat=51.8719444274902, lng=4.99277782440186),
 8400069: StationInfo(name='Arnemuiden', lat=51.5016670227051, lng=3.66916656494141),
 8400075: StationInfo(name='Arnhem Presikhaaf', lat=51.9880561828613, lng=5.94388866424561),
 8400072: StationInfo(name='Arnhem Velperpoort', lat=51.985279083252, lng=5.91944456100464),
 8400227: StationInfo(name='Arnhem Zuid', lat=51.9550018310547, lng=5.85194444656372),
 8400089: StationInfo(name='Baflo', lat=53.3608969, lng=6.5185581),
 8400090: StationInfo(name='Barendrecht', lat=51.8547210693359, lng=4.5533332824707),
 8400091: StationInfo(name='Barneveld Centrum', lat=52.1399993896484, lng=5.59027767181396),
 8400092: StationInfo(name='Barneveld Noord', lat=52.1613883972168, lng=5.59805536270142),
 8400115: StationInfo(name='Barneveld Zuid', lat=52.128853, lng=5.60246),
 8400094: StationInfo(name='Bedum', lat=53.3068857, lng=6.593054),
 8400096: StationInfo(name='Beek-Elsloo', lat=50.9474983215332, lng=5.78666687011719),
 8400097: StationInfo(name='Beesd', lat=51.8994445800781, lng=5.19444465637207),
 8400100: StationInfo(name='Beilen', lat=52.8547210693359, lng=6.52111101150513),
 8400108: StationInfo(name='Bergen op Zoom', lat=51.4938888549805, lng=4.29611110687256),
 8400112: StationInfo(name='Best', lat=51.5099983215332, lng=5.38916683197022),
 8400113: StationInfo(name='Beverwijk', lat=52.4783325195313, lng=4.65666675567627),
 8400114: StationInfo(name='Bilthoven', lat=52.1300010681152, lng=5.20388889312744),
 8400117: StationInfo(name='Blerick', lat=51.372501373291, lng=6.15500020980835),
 8400118: StationInfo(name='Bloemendaal', lat=52.404167175293, lng=4.62750005722046),
 8400121: StationInfo(name='Bodegraven', lat=52.0813903808594, lng=4.7461109161377),
 8400124: StationInfo(name='Borne', lat=52.2988891601562, lng=6.74805545806885),
 8400125: StationInfo(name='Boskoop', lat=52.0777778625488, lng=4.64694452285767),
 8400126: StationInfo(name='Boskoop Snijdelwijk', lat=52.067658, lng=4.646186),
 8400236: StationInfo(name='Boven-Hardinxveld', lat=51.832222, lng=4.878056),
 8400230: StationInfo(name='Bovenkarspel Flora', lat=52.6961097717285, lng=5.25277757644653),
 8400127: StationInfo(name='Bovenkarspel-Grootebroek', lat=52.6949996948242, lng=5.23777770996094),
 8400132: StationInfo(name='Breda-Prinsenbeek', lat=51.606388092041, lng=4.72083330154419),
 8400136: StationInfo(name='Brummen', lat=52.0911102294922, lng=6.14694452285767),
 8400140: StationInfo(name='Bunde', lat=50.8969459533691, lng=5.73666667938232),
 8400141: StationInfo(name='Bunnik', lat=52.0630569458008, lng=5.19444465637207),
 8400145: StationInfo(name='Bussum Zuid', lat=52.2658348083496, lng=5.16305541992188),
 8400147: StationInfo(name='Capelle Schollevaar', lat=51.9541664123535, lng=4.58416652679443),
 8400152: StationInfo(name='Chevremont', lat=50.8761100769043, lng=6.05972242355347),
 8400155: StationInfo(name='Cuijk', lat=51.7266825879048, lng=5.87429523468017),
 8400154: StationInfo(name='Culemborg', lat=51.9466667175293, lng=5.22694444656372),
 8400164: StationInfo(name='Daarlerveen', lat=52.4407702, lng=6.5759947),
 8400161: StationInfo(name='Dalen', lat=52.6941680908203, lng=6.75805568695068),
 8400188: StationInfo(name='De Vink', lat=52.1472206115723, lng=4.4563889503479),
 8400745: StationInfo(name='De Westereen', lat=53.24817, lng=6.03463),
 8400168: StationInfo(name='Deinum', lat=53.1888115, lng=5.7281572),
 8400169: StationInfo(name='Delden', lat=52.2599983215332, lng=6.7161111831665),
 8400166: StationInfo(name='Delft Campus', lat=51.9908332824707, lng=4.36472225189209),
 8400171: StationInfo(name='Delfzijl', lat=53.3336625, lng=6.9240797),
 8400175: StationInfo(name='Delfzijl West', lat=53.3320834, lng=6.9069092),
 8400278: StationInfo(name='Den Haag Mariahoeve', lat=52.0905570983887, lng=4.36944437026978),
 8400279: StationInfo(name='Den Haag Moerwijk', lat=52.0538902282715, lng=4.3086109161377),
 8400379: StationInfo(name='Den Haag Ypenburg', lat=52.0552787780762, lng=4.39222240447998),
 8400303: StationInfo(name='Den Helder Zuid', lat=52.9324989318848, lng=4.76416683197022),
 8400172: StationInfo(name='Deurne', lat=51.4558334350586, lng=5.78888893127441),
 8400185: StationInfo(name='Deventer Colmschate', lat=52.2502784729004, lng=6.21444463729858),
 8400174: StationInfo(name='Didam', lat=51.933502, lng=6.1324106),
 8400165: StationInfo(name='Diemen', lat=52.34515, lng=4.967566),
 8400163: StationInfo(name='Diemen Zuid', lat=52.3302764892578, lng=4.95583343505859),
 8400184: StationInfo(name='Doetinchem De Huet', lat=51.9591413, lng=6.2598521),
 8400186: StationInfo(name='Dordrecht Stadspolders', lat=51.801944732666, lng=4.71666669845581),
 8400181: StationInfo(name='Dordrecht Zuid', lat=51.7900009155273, lng=4.67138910293579),
 8400183: StationInfo(name='Driehuis', lat=52.4425010681152, lng=4.63805532455444),
 8400192: StationInfo(name='Dronryp', lat=53.1778086, lng=5.6347411),
 8400198: StationInfo(name='Dronten', lat=52.5344, lng=5.72089),
 8400193: StationInfo(name='Duiven', lat=51.9433326721191, lng=6.01472234725952),
 8400195: StationInfo(name='Echt', lat=51.1005554199219, lng=5.87888908386231),
 8400201: StationInfo(name='Ede Centrum', lat=52.0436096191406, lng=5.66833353042603),
 8400202: StationInfo(name='Eemshaven', lat=53.458419, lng=6.832),
 8400219: StationInfo(name='Eijsden', lat=50.7719459533691, lng=5.71000003814697),
 8400196: StationInfo(name='Eindhoven Strijp-S', lat=51.4511108398438, lng=5.45583343505859),
 8400210: StationInfo(name='Enkhuizen', lat=52.6991653442383, lng=5.28638887405396),
 8400217: StationInfo(name='Enschede De Eschmarke', lat=52.2213897705078, lng=6.95111131668091),
 8400221: StationInfo(name='Enschede Kennispark', lat=52.2374992370605, lng=6.83888912200928),
 8400216: StationInfo(name='Ermelo', lat=52.3016662597656, lng=5.61472225189209),
 8400338: StationInfo(name='Eygelshoven', lat=50.8905563354492, lng=6.04500007629395),
 8400234: StationInfo(name='Eygelshoven Markt', lat=50.8960498196442, lng=6.0602474212646396),
 8400638: StationInfo(name='Feanwâlden', lat=53.2351834, lng=5.9886615),
 8400232: StationInfo(name='Franeker', lat=53.1824488, lng=5.5483094),
 8400241: StationInfo(name='Gaanderen', lat=51.93074, lng=6.3486),
 8400246: StationInfo(name='Geleen Oost', lat=50.9669456481934, lng=5.84305572509766),
 8400248: StationInfo(name='Geleen-Lutterade', lat=50.9755554199219, lng=5.82472229003906),
 8400251: StationInfo(name='Gilze-Rijen', lat=51.583610534668, lng=4.92611122131348),
 8400262: StationInfo(name='Glanerbrug', lat=52.2186126708984, lng=6.97444438934326),
 8400253: StationInfo(name='Goes', lat=51.4980545043945, lng=3.89055562019348),
 8400254: StationInfo(name='Goor', lat=52.2302780151367, lng=6.58444452285767),
 8400257: StationInfo(name='Gouda Goverwelle', lat=52.0149993896484, lng=4.7408332824707),
 8400259: StationInfo(name='Gramsbergen', lat=52.6091651916504, lng=6.67583322525024),
 8400267: StationInfo(name='Grijpskerk', lat=53.2557403255735, lng=6.30977869033813),
 8400238: StationInfo(name='Groningen Europapark', lat=53.20480027, lng=6.5854178),
 8400264: StationInfo(name='Groningen Noord', lat=53.2301469, lng=6.5563172),
 8400266: StationInfo(name='Grou-Jirnsum', lat=53.0888900756836, lng=5.82250022888184),
 8400270: StationInfo(name='Haarlem Spaarnwoude', lat=52.3827781677246, lng=4.67305564880371),
 8400400: StationInfo(name='Halfweg-Zwanenburg', lat=52.385935, lng=4.747165),
 8400438: StationInfo(name='Hardinxveld Blauwe Zoom', lat=51.82944, lng=4.815663),
 8400295: StationInfo(name='Hardinxveld-Giessendam', lat=51.8305549621582, lng=4.83583354949951),
 8400297: StationInfo(name='Haren', lat=53.1761093139648, lng=6.61722230911255),
 8400296: StationInfo(name='Harlingen', lat=53.1704205, lng=5.4251932),
 8400298: StationInfo(name='Harlingen Haven', lat=53.174917, lng=5.4112885),
 8400317: StationInfo(name='Heemskerk', lat=52.4952774047852, lng=4.68694448471069),
 8400404: StationInfo(name='Heerlen Woonboulevard', lat=50.896667, lng=5.952222),

In [16]:
geolocator = Nominatim(user_agent="ns_train_stations_scraper")
geolocator_rate_limited = RateLimiter(geolocator.reverse, min_delay_seconds=2)

In [17]:
addresses_pkl = raw_out_dir / 'addresses.pkl'
if not addresses_pkl.exists():
    sql_stations = pd.DataFrame({
        'uic': uic,
        'name': v.name,
        'lat': v.lat,
        'lng': v.lng,
        'address': geolocator_rate_limited(f"{v.lat}, {v.lng}").address,
    }   for uic, v in stations_by_uicCode.items())
    with open(addresses_pkl, 'xb') as file:
        pickle.dump(sql_stations, file, protocol=-1)
else:
    with open(addresses_pkl, 'r+b') as file:
        sql_stations = pickle.load(file)

In [18]:
sql_trainsetamenities = pd.DataFrame([
    {
        'trainset': trainset,
        'amenity': amenity,
    }
    for trainset, facilities in facilities_by_trainType.items()
    for amenity in facilities
])
sql_trainsetamenities

   trainset       amenity
0     Flirt        TOILET
1     Flirt        STROOM
2     Flirt         FIETS
3     Flirt  TOEGANKELIJK
4     Flirt          WIFI
5       SNG         FIETS
6       SNG          WIFI
7       SNG        STROOM
8       SNG  TOEGANKELIJK
9       SNG        TOILET
10      SLT         FIETS
11      SLT        TOILET
12      SLT  TOEGANKELIJK
13     ICNG          WIFI
14     ICNG        TOILET
15     ICNG        STILTE
16     ICNG        STROOM
17     ICNG         FIETS
18     ICNG  TOEGANKELIJK
19      ICM          WIFI
20      ICM        TOILET
21      ICM        STILTE
22      ICM        STROOM
23      ICM         FIETS
24      DDZ          WIFI
25      DDZ        TOILET
26      DDZ        STILTE
27      DDZ        STROOM
28      DDZ         FIETS
29     VIRM          WIFI
30     VIRM        TOILET
31     VIRM        STILTE
32     VIRM         FIETS
33     VIRM        STROOM

In [39]:
sql_passservice = pd.DataFrame([
    {
        'num': k,
        'name': f"{v.categoryName} {v.ritnummer} to {v.stops[-1].name}",
        'trainset': v.trainType if v.trainType
                    else TrainType.SLT if v.ritnummer == 9571
                    else TrainType.ICNG if v.categoryCode == CategoryCode.ECD
                    else TrainType.VIRM if v.categoryCode == CategoryCode.IC
                    else None,
    }
    for k, v in train_timetables.items()
])

In [40]:
sql_stop = pd.DataFrame([
    {
        'passservice_num': passservice_id,
        'arrival': stop.arrives,
        'departure': stop.departs,
        'stations_uic': stop.station_uic,
    }
    for passservice_id, passservice in train_timetables.items()
    for stop in passservice.stops
])

## Final cleanup/asserts

In [41]:
# delete rows missing both arrival/departure
sql_stop = sql_stop[~sql_stop[['arrival', 'departure']].isna().all(axis='columns')]

In [42]:
sql_stop.loc[sql_stop['arrival'] == sql_stop['departure'], 'departure'] += timedelta(seconds=30)
sql_stop.loc[sql_stop['arrival'] == sql_stop['departure']]

Empty DataFrame
Columns: [passservice_num, arrival, departure, stations_uic]
Index: []

In [43]:
# double-check, in sql_stop, that only first and last stops are missing arrival/departure
stops_sorted_groups = sql_stop.sort_values('arrival', na_position='first').groupby('passservice_num')
heads_departures = stops_sorted_groups.apply(lambda group: group['departure'].iloc[:-1])
tails_arrivals = stops_sorted_groups.apply(lambda group: group['arrival'].iloc[1:])
assert(heads_departures.notna().all().all())
assert(tails_arrivals.notna().all().all())

In [44]:
# fill first arrival, last departure with midnight the day before/after
first_arrival_update = sql_stop[['passservice_num', 'arrival']]
first_arrival_update = first_arrival_update.sort_values('arrival', na_position='first')
first_arrival_update['arrival'] = first_arrival_update['arrival'].dt.floor('D')
first_arrival_update['arrival'] = first_arrival_update.groupby('passservice_num')['arrival'].bfill(limit=1)
first_arrival_update = first_arrival_update.groupby('passservice_num').nth(0)
sql_stop['arrival'] = first_arrival_update['arrival'].reindex_like(sql_stop).where(pd.notna, sql_stop['arrival'])

last_departure_update = sql_stop[['passservice_num', 'arrival', 'departure']]
last_departure_update = last_departure_update.sort_values('arrival', na_position='first')
last_departure_update['departure'] = last_departure_update['departure'].dt.ceil('D')
last_departure_update['departure'] = last_departure_update.groupby('passservice_num')['departure'].ffill(limit=1)
last_departure_update = last_departure_update.groupby('passservice_num').nth(-1)
sql_stop['departure'] = last_departure_update['departure'].reindex_like(sql_stop).where(pd.notna, sql_stop['departure'])

In [45]:
# double-check table keys
assert set(sql_stop['stations_uic']) < set(sql_stations['uic'])

trainsets = [
    set(sql_passservice['trainset']),
    set(sql_trainsetamenities['trainset']),
]
assert trainsets[0] == trainsets[1], trainsets

passservice_nums = [
    set(sql_stop['passservice_num']),
    set(sql_passservice['num']),
]
assert passservice_nums[0] == passservice_nums[1], passservice_nums

In [46]:
# also check which columns of any tables are nullable
assert (sql_stop.notna().all().all())
assert (sql_stations.notna().all().all())
assert (sql_passservice.notna().all().all())
assert (sql_trainsetamenities.notna().all().all())
# print('sql_stop', sql_stop.notna().all(axis='index'))
# print('sql_stations', sql_stations.notna().all(axis='index'))
# print('sql_passservice', sql_passservice.notna().all(axis='index'))
# print('sql_trainsetamenities', sql_trainsetamenities.notna().all(axis='index'))

## Export

In [47]:
# export with .to_csv()
sql_stations.to_csv(out_dir / 'stations.csv')
sql_trainsetamenities.to_csv(out_dir / 'trainsetamenities.csv')
sql_passservice.to_csv(out_dir / 'passservice.csv')
sql_stop.to_csv(out_dir / 'stop.csv')

# UNUSED BELOW

## Get train stock

In [ ]:
# TREIN '/v1/trein' https://apiportal.ns.nl/api-details#api=virtual-train-API&operation=getTrainInformation
# TREINRIT '/v1/trein/{ritnummer}' https://apiportal.ns.nl/api-details#api=virtual-train-API&operation=getTrainInformationForRitnummer
# STATION VAN TREINRIT '/v1/trein/{ritnummer}/{stationscode}' https://apiportal.ns.nl/api-details#api=virtual-train-API&operation=getTrainInformationForRitnummerAndStationCode

# (Below are available from the three APIs above, but not all are applicable without specifying Rit and/or Station.)
# (Één MaterieelDeel bestaat uit meerdere Bakken.)

# TreinInformatie.ritnummer (int)
# TreinInformatie.type (string)
# TreinInformatie.geplandeMaterieeldelen[].materieelType (string)
# TreinInformatie.geplandeMaterieeldelen[].materieelnummer (int)
# TreinInformatie.geplandeMaterieeldelen[].type (string)
# TreinInformatie.geplandeMaterieeldelen[].faciliteiten (string[])

In [ ]:
# trein_pkl = Path('./ns_results/raw/trein_info.pkl')
# if not trein_pkl.exists():
#     response = requests.get(NSAPI_URLS['VIRTUAL_TRAIN'] + '/v1' + '/trein', headers=NS_GET_HEADER,
#         params=nsapi.virtual_train.ApiV1TreinGetParameters(
#             ids=train_id,
#             # dateTime=(datetime.today() + timedelta(days=1)).isoformat().__str__(),
#             all=True,
#         )
#     )
#     print('Response:', response.json())
#     obj = nsapi.virtual_train.TreinInformatie(**response.json())
#     with open(trein_pkl, 'wb') as file:
#         pickle.dump(obj, file, protocol=-1)
# else:
#     with open(trein_pkl, 'rb') as file:
#         obj = pickle.load(file)

In [ ]:
# do we want to do /trein/ritnummer?
# trein_rit_pkl = Path('./ns_results/raw/trein_met_ritnummer_info.pkl')
# if not trein_rit_pkl.exists():
#     response = requests.get(NSAPI_URLS['VIRTUAL_TRAIN'] + '/v1' + f'/trein/{ritnummer}', headers=NS_GET_HEADER,
#         params=nsapi.virtual_train.ApiV1TreinRitnummerGetParameters(
#             # countryCodes=['NL'],
#             # limit=None # irrelevant when not providing str `q`
#         )
#     )
#     obj = nsapi.virtual_train.TreinInformatie(**response.json())
#     with open(trein_rit_pkl, 'wb') as file:
#         pickle.dump(obj, file, protocol=-1)
# else:
#     with open(trein_rit_pkl, 'rb') as file:
#         obj = pickle.load(file)

In [ ]:
# do we want to do /trein/ritnummer/stationscode?
# trein_rit_stations_pkl = Path('./ns_results/raw/trein_met_ritnummer_en_stationscode_info.pkl')
# if not trein_rit_stations_pkl.exists():
#     response = requests.get(NSAPI_URLS['VIRTUAL_TRAIN'] + '/v1' + f'/trein/{ritnummer}/{stationscode}', headers=NS_GET_HEADER,
#         params=nsapi.virtual_train.ApiV1TreinRitnummerStationscodeGetParameters(
#             # countryCodes=['NL'],
#             # limit=None # irrelevant when not providing str `q`
#         )
#     )
#     obj = nsapi.virtual_train.TreinInformatie(**response.json())
#     with open(trein_rit_stations_pkl, 'wb') as file:
#         pickle.dump(obj, file, protocol=-1)
# else:
#     with open(trein_rit_stations_pkl, 'rb') as file:
#         obj = pickle.load(file)

## Other data

In [ ]:
# ARRIVALS 'https://gateway.apiportal.ns.nl/timetable-api/v2/arrivals' https://apiportal.ns.nl/api-details#api=reisinformatie-api&operation=getArrivals&definition=Arrival
# DEPARTURES 'https://gateway.apiportal.ns.nl/timetable-api/v2/departures' https://apiportal.ns.nl/api-details#api=reisinformatie-api&operation=getDepartures
# Arrivals[].plannedTimeZoneOffset
# Arrivals[].plannedDateTime
# Arrivals[].name
# Arrivals[].trainCategory
#   Arrivals[].product.displayName
#   Arrivals[].product.shortCategoryName
# Arrivals[].product.number (string)

In [ ]:
# arrivals_pkl = Path('./ns_results/raw/arrivals.pkl')
# if not arrivals_pkl.exists():
#     response = requests.get('https://gateway.apiportal.ns.nl/timetable-api' + '/v2' + '/arrivals', headers=NS_GET_HEADER,
#         params=nsapi.reisinformatie.ApiV2ArrivalsGetParameters(
#             # uicCode=station_uic_code
#             maxJourneys=100 # default 40
#         )
#     )
#     obj = nsapi.reisinformatie.RepresentationResponseArrivalsPayload(**response.json())
#     with open(arrivals_pkl, 'wb') as file:
#         pickle.dump(obj, file, protocol=-1)
# else:
#     with open(arrivals_pkl, 'rb') as file:
#         obj = pickle.load(file)

In [ ]:
# departures_pkl = Path('./ns_results/raw/departures.pkl')
# if not departures_pkl.exists():
#     response = requests.get('https://gateway.apiportal.ns.nl/timetable-api' + '/v2' + '/departures', headers=NS_GET_HEADER,
#         params=nsapi.reisinformatie.ApiV2DeparturesGetParameters(
#             # uicCode=station_uic_code
#             maxJourneys=100, # default 40
#         )
#     )
#     obj = nsapi.reisinformatie.RepresentationResponseDeparturesPayload(**response.json())
#     with open(departures_pkl, 'wb') as file:
#         pickle.dump(obj, file, protocol=-1)
# else:
#     with open(departures_pkl, 'rb') as file:
#         obj = pickle.load(file)