In [1]:
from pathlib import Path
print(Path("./").resolve())

import os
import importlib
from pydantic import AwareDatetime, BaseModel
from typing import *
from enum import StrEnum
from zoneinfo import ZoneInfo
from datetime import datetime, timedelta, timezone, date
from pathlib import Path
from tqdm import tqdm
from itertools import chain, islice
from collections import defaultdict
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd
import yaml
import json
import requests
import pickle
import configparser
import nsapi

C:\Users\jeffw\Code\IDEA\dutch_railways_server\database\src\scraping

In [2]:
working_dir = "./"

In [3]:
# Parameters
working_dir = "C:\\Users\\jeffw\\Code\\IDEA\\dutch_railways_server\\database\\build\\scraping"

In [4]:
out_dir = Path(working_dir) / 'ns_results'
raw_out_dir = out_dir / 'raw'
out_dir.mkdir(parents=True, exist_ok=True)
raw_out_dir.mkdir(parents=True, exist_ok=True)

In [5]:
NS_PRIMARY_KEY = os.environ["NS_PRIMARY_KEY"]
NS_SECONDARY_KEY = os.environ["NS_SECONDARY_KEY"]

NS_GET_HEADER = {
    'Ocp-Apim-Subscription-Key': NS_PRIMARY_KEY,
}

# https://apiportal.ns.nl/apis
NSAPI_URLS = {}
with open('./nsapi/_nsapp-stations-api.yaml') as file:
    NSAPI_URLS['STATIONS']       = yaml.full_load(file)['servers'][0]['url']
with open('./nsapi/_reisinformatie-api.yaml') as file:
    NSAPI_URLS['REISINFORMATIE'] = yaml.full_load(file)['servers'][0]['url']
with open('./nsapi/_virtual-train-API.yaml') as file:
    NSAPI_URLS['VIRTUAL_TRAIN']  = yaml.full_load(file)['servers'][0]['url']

In [6]:
# below not useful (only works with API at foreign station departures)
# FOR_DATE: AwareDatetime = datetime(year=2026, month=6, day=1, tzinfo=ZoneInfo('Europe/Amsterdam'))

## Get train trips

In [7]:
# VEHICLE '/vehicle' https://apiportal.ns.nl/api-details#api=virtual-train-API&operation=getVehicles
# treinen[].ritId (string)
# treinen[].richting (float)
# treinen[].type (string)

In [8]:
vehicles_pkl = raw_out_dir / 'vehicle.pkl'
if not vehicles_pkl.exists():
    response = requests.get(NSAPI_URLS['VIRTUAL_TRAIN'] + '/vehicle', headers=NS_GET_HEADER,
        params=nsapi.virtual_train.ApiVehicleGetParameters(
            lat=52.366667, long=4.883333,
            radius=300000,
            # limit=None,
            # route=route_number,
            # features=materieel_value,
        )
    )
    print('Response:', response.json())
    obj = nsapi.virtual_train.Treinen(**response.json()['payload'])
    with open(vehicles_pkl, 'wb') as file:
        pickle.dump(obj, file, protocol=-1)
else:
    with open(vehicles_pkl, 'rb') as file:
        obj = pickle.load(file)

Response: {'payload': {'treinen': [{'treinNummer': 8758, 'ritId': '8758', 'lat': 52.077145, 'lng': 4.6467066, 'snelheid': 0.06, 'richting': 5.67, 'horizontaleNauwkeurigheid': 280272.22, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6461, 'ritId': '6461', 'lat': 51.329002, 'lng': 5.611201, 'snelheid': 139.92, 'richting': 154.06, 'horizontaleNauwkeurigheid': 280233.34, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6561, 'ritId': '6561', 'lat': 51.45571, 'lng': 5.7896214, 'snelheid': 0.0, 'richting': 105.62, 'horizontaleNauwkeurigheid': 280155.56, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6669, 'ritId': '6669', 'lat': 51.95502, 'lng': 5.851888, 'snelheid': 44.85, 'richting': 176.95, 'horizontaleNauwkeurigheid': 280427.78, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 7663, 'ritId': '7663', 'lat': 51.987793, 'lng': 5.9434123, 'snelheid': 0.0, 'richting': 58.41, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6565, 'ritId': '6565', 'lat': 51.663467, 'lng': 5.2904844, 'snelheid': 79.95, 'richting': 174.3, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6563, 'ritId': '6563', 'lat': 51.44295, 'lng': 5.480355, 'snelheid': 0.0, 'richting': 83.06, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6463, 'ritId': '6463', 'lat': 51.496964, 'lng': 5.400713, 'snelheid': 139.12, 'richting': 150.58, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 7665, 'ritId': '7665', 'lat': 51.844112, 'lng': 5.8530517, 'snelheid': 0.0, 'richting': 16.09, 'horizontaleNauwkeurigheid': 280777.78, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 9063, 'ritId': '9063', 'lat': 52.515736, 'lng': 6.159371, 'snelheid': 138.41, 'richting': 52.1, 'horizontaleNauwkeurigheid': 280155.56, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 9068, 'ritId': '9068', 'lat': 52.913055, 'lng': 5.968163, 'snelheid': 132.0, 'richting': 148.35, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5664, 'ritId': '5664', 'lat': 52.247932, 'lng': 5.5508666, 'snelheid': 134.13, 'richting': 228.74, 'horizontaleNauwkeurigheid': 280700.0, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6159, 'ritId': '6159', 'lat': 52.889893, 'lng': 6.533936, 'snelheid': 142.62, 'richting': 12.34, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5760, 'ritId': '5760', 'lat': 52.35167, 'lng': 4.9514155, 'snelheid': 50.04, 'richting': 304.27, 'horizontaleNauwkeurigheid': 280427.78, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4169, 'ritId': '4169', 'lat': 52.388317, 'lng': 4.8351774, 'snelheid': 33.2, 'richting': 122.77, 'horizontaleNauwkeurigheid': 280466.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5160, 'ritId': '5160', 'lat': 51.907448, 'lng': 4.507284, 'snelheid': 84.6, 'richting': 325.87, 'horizontaleNauwkeurigheid': 284277.78, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5661, 'ritId': '5661', 'lat': 52.462456, 'lng': 6.011557, 'snelheid': 119.91, 'richting': 29.18, 'horizontaleNauwkeurigheid': 280738.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5965, 'ritId': '5965', 'lat': 51.54108, 'lng': 4.4596477, 'snelheid': 0.0, 'richting': 225.21, 'horizontaleNauwkeurigheid': 280894.44, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 8460, 'ritId': '8460', 'lat': 52.393993, 'lng': 4.8627524, 'snelheid': 75.43, 'richting': 133.51, 'horizontaleNauwkeurigheid': 280466.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4857, 'ritId': '4857', 'lat': 52.637665, 'lng': 4.739601, 'snelheid': 0.0, 'richting': 29.18, 'horizontaleNauwkeurigheid': 280622.22, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 8863, 'ritId': '8863', 'lat': 51.692516, 'lng': 5.29434, 'snelheid': 31.89, 'richting': 194.24, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 8864, 'ritId': '8864', 'lat': 51.952076, 'lng': 5.221722, 'snelheid': 95.97, 'richting': 329.18, 'horizontaleNauwkeurigheid': 280116.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6964, 'ritId': '6964', 'lat': 52.04361, 'lng': 5.161718, 'snelheid': 114.37, 'richting': 337.47, 'horizontaleNauwkeurigheid': 280116.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4963, 'ritId': '4963', 'lat': 52.110203, 'lng': 5.126301, 'snelheid': 0.0, 'richting': 250.45, 'horizontaleNauwkeurigheid': 280427.78, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4967, 'ritId': '4967', 'lat': 52.221558, 'lng': 4.54755, 'snelheid': 132.91, 'richting': 65.49, 'horizontaleNauwkeurigheid': 280505.56, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4069, 'ritId': '4069', 'lat': 52.324818, 'lng': 4.934778, 'snelheid': 57.13, 'richting': 145.6, 'horizontaleNauwkeurigheid': 280466.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6069, 'ritId': '6069', 'lat': 52.100098, 'lng': 4.938813, 'snelheid': 134.96, 'richting': 61.93, 'horizontaleNauwkeurigheid': 280505.56, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 8869, 'ritId': '8869', 'lat': 52.131676, 'lng': 4.537764, 'snelheid': 129.74, 'richting': 118.5, 'horizontaleNauwkeurigheid': 280661.12, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5456, 'ritId': '5456', 'lat': 52.387836, 'lng': 4.638795, 'snelheid': 0.0, 'richting': 98.64, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6967, 'ritId': '6967', 'lat': 52.027596, 'lng': 5.172384, 'snelheid': 77.29, 'richting': 157.1, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5863, 'ritId': '5863', 'lat': 52.159782, 'lng': 5.384929, 'snelheid': 90.68, 'richting': 37.48, 'horizontaleNauwkeurigheid': 280544.44, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4856, 'ritId': '4856', 'lat': 52.38879, 'lng': 4.833515, 'snelheid': 75.74, 'richting': 92.34, 'horizontaleNauwkeurigheid': 280933.34, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4258, 'ritId': '4258', 'lat': 52.080387, 'lng': 4.3464, 'snelheid': 78.19, 'richting': 53.63, 'horizontaleNauwkeurigheid': 280505.56, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 704364, 'ritId': '704364', 'lat': 52.403778, 'lng': 5.30139, 'snelheid': 61.7, 'richting': 238.52, 'horizontaleNauwkeurigheid': 280661.12, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4367, 'ritId': '4367', 'lat': 52.33723, 'lng': 4.81075, 'snelheid': 128.19, 'richting': 58.63, 'horizontaleNauwkeurigheid': 280272.22, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 304065, 'ritId': '304065', 'lat': 51.95178, 'lng': 4.553468, 'snelheid': 0.0, 'richting': 263.24, 'horizontaleNauwkeurigheid': 280311.12, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6663, 'ritId': '6663', 'lat': 51.591633, 'lng': 4.872816, 'snelheid': 130.08, 'richting': 283.17, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6662, 'ritId': '6662', 'lat': 51.69077, 'lng': 5.294025, 'snelheid': 0.0, 'richting': 22.84, 'horizontaleNauwkeurigheid': 280466.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6660, 'ritId': '6660', 'lat': 51.811485, 'lng': 5.730542, 'snelheid': 22.39, 'richting': 71.59, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6661, 'ritId': '6661', 'lat': 51.801697, 'lng': 4.6785445, 'snelheid': 33.48, 'richting': 14.01, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 7462, 'ritId': '7462', 'lat': 52.078835, 'lng': 5.121802, 'snelheid': 0.0, 'richting': 295.35, 'horizontaleNauwkeurigheid': 280194.44, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5864, 'ritId': '5864', 'lat': 52.186455, 'lng': 5.42346, 'snelheid': 100.18, 'richting': 225.96, 'horizontaleNauwkeurigheid': 280233.34, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4060, 'ritId': '4060', 'lat': 52.339382, 'lng': 4.921793, 'snelheid': 75.16, 'richting': 334.33, 'horizontaleNauwkeurigheid': 280233.34, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4063, 'ritId': '4063', 'lat': 52.01508, 'lng': 4.740759, 'snelheid': 0.0, 'richting': 275.56, 'horizontaleNauwkeurigheid': 280311.12, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4058, 'ritId': '4058', 'lat': 52.467957, 'lng': 4.805209, 'snelheid': 33.62, 'richting': 1.64, 'horizontaleNauwkeurigheid': 280466.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4369, 'ritId': '4369', 'lat': 52.171387, 'lng': 4.488495, 'snelheid': 79.34, 'richting': 37.71, 'horizontaleNauwkeurigheid': 280311.12, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 8867, 'ritId': '8867', 'lat': 52.099712, 'lng': 5.053878, 'snelheid': 70.56, 'richting': 94.29, 'horizontaleNauwkeurigheid': 280155.56, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4360, 'ritId': '4360', 'lat': 52.326332, 'lng': 4.785723, 'snelheid': 127.4, 'richting': 251.53, 'horizontaleNauwkeurigheid': 284316.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4962, 'ritId': '4962', 'lat': 52.318897, 'lng': 5.030751, 'snelheid': 89.6, 'richting': 307.45, 'horizontaleNauwkeurigheid': 280505.56, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5461, 'ritId': '5461', 'lat': 52.38838, 'lng': 4.637177, 'snelheid': 0.0, 'richting': 306.77, 'horizontaleNauwkeurigheid': 280194.44, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5767, 'ritId': '5767', 'lat': 52.353214, 'lng': 4.947585, 'snelheid': 34.19, 'richting': 124.35, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5060, 'ritId': '5060', 'lat': 51.92193, 'lng': 4.4096527, 'snelheid': 24.78, 'richting': 281.8, 'horizontaleNauwkeurigheid': 280311.12, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5255, 'ritId': '5255', 'lat': 51.8546, 'lng': 4.5532966, 'snelheid': 10.82, 'richting': 137.26, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5258, 'ritId': '5258', 'lat': 52.024963, 'lng': 4.3382072, 'snelheid': 125.25, 'richting': 321.77, 'horizontaleNauwkeurigheid': 280777.78, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5665, 'ritId': '5665', 'lat': 52.13031, 'lng': 5.2054253, 'snelheid': 24.45, 'richting': 66.61, 'horizontaleNauwkeurigheid': 280427.78, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5662, 'ritId': '5662', 'lat': 52.13016, 'lng': 5.2043266, 'snelheid': 0.0, 'richting': 246.75, 'horizontaleNauwkeurigheid': 280155.56, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5865, 'ritId': '5865', 'lat': 52.30522, 'lng': 5.057479, 'snelheid': 111.28, 'richting': 116.33, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5666, 'ritId': '5666', 'lat': 52.453815, 'lng': 6.002109, 'snelheid': 46.07, 'richting': 226.27, 'horizontaleNauwkeurigheid': 280466.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 7362, 'ritId': '7362', 'lat': 52.065884, 'lng': 5.325971, 'snelheid': 140.17, 'richting': 269.3, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4158, 'ritId': '4158', 'lat': 52.644672, 'lng': 5.044465, 'snelheid': 40.94, 'richting': 70.55, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 5257, 'ritId': '5257', 'lat': 52.014824, 'lng': 4.3500175, 'snelheid': 102.43, 'richting': 148.22, 'horizontaleNauwkeurigheid': 284588.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 6166, 'ritId': '6166', 'lat': 52.536663, 'lng': 6.189528, 'snelheid': 139.86, 'richting': 202.32, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 7460, 'ritId': '7460', 'lat': 52.293156, 'lng': 4.9646645, 'snelheid': 69.84, 'richting': 331.56, 'horizontaleNauwkeurigheid': 280427.78, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 9061, 'ritId': '9061', 'lat': 52.89375, 'lng': 5.9883776, 'snelheid': 136.05, 'richting': 323.8, 'horizontaleNauwkeurigheid': 280116.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 9064, 'ritId': '9064', 'lat': 52.547894, 'lng': 5.558025, 'snelheid': 137.91, 'richting': 267.51, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4171, 'ritId': '4171', 'lat': 52.546703, 'lng': 4.999632, 'snelheid': 137.25, 'richting': 183.63, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 8469, 'ritId': '8469', 'lat': 52.394386, 'lng': 4.8412404, 'snelheid': 68.83, 'richting': 233.55, 'horizontaleNauwkeurigheid': 280622.22, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 8367, 'ritId': '8367', 'lat': 52.326466, 'lng': 4.7862883, 'snelheid': 129.77, 'richting': 251.81, 'horizontaleNauwkeurigheid': 288166.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4160, 'ritId': '4160', 'lat': 52.406464, 'lng': 4.8033223, 'snelheid': 114.57, 'richting': 2.5, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4859, 'ritId': '4859', 'lat': 52.47288, 'lng': 4.6511683, 'snelheid': 74.71, 'richting': 11.54, 'horizontaleNauwkeurigheid': 280466.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 4964, 'ritId': '4964', 'lat': 52.11042, 'lng': 5.127503, 'snelheid': 43.46, 'richting': 69.58, 'horizontaleNauwkeurigheid': 280816.66, 'type': 'SPR', 'bron': 'OBIS'}, {'treinNummer': 1162, 'ritId': '1162', 'lat': 51.681076, 'lng': 4.668815, 'snelheid': 112.31, 'richting': 337.81, 'horizontaleNauwkeurigheid': 280505.56, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 761, 'ritId': '761', 'lat': 52.685074, 'lng': 6.1958137, 'snelheid': 76.28, 'richting': 6.08, 'horizontaleNauwkeurigheid': 280194.44, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 1858, 'ritId': '1858', 'lat': 51.841335, 'lng': 4.5751543, 'snelheid': 135.89, 'richting': 140.54, 'horizontaleNauwkeurigheid': 280233.34, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 1164, 'ritId': '1164', 'lat': 51.57126, 'lng': 5.1465516, 'snelheid': 95.39, 'richting': 249.69, 'horizontaleNauwkeurigheid': 280194.44, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 1167, 'ritId': '1167', 'lat': 51.669006, 'lng': 4.6770515, 'snelheid': 133.29, 'richting': 156.63, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 765, 'ritId': '765', 'lat': 52.20242, 'lng': 5.2907944, 'snelheid': 102.8, 'richting': 139.49, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 1165, 'ritId': '1165', 'lat': 51.585773, 'lng': 5.2214394, 'snelheid': 128.83, 'richting': 86.12, 'horizontaleNauwkeurigheid': 280311.12, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 2460, 'ritId': '2460', 'lat': 51.976498, 'lng': 4.4689593, 'snelheid': 188.61, 'richting': 208.04, 'horizontaleNauwkeurigheid': 280233.34, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 1871, 'ritId': '1871', 'lat': 51.879864, 'lng': 4.531882, 'snelheid': 137.63, 'richting': 332.28, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 2461, 'ritId': '2461', 'lat': 52.385498, 'lng': 4.839055, 'snelheid': 61.98, 'richting': 349.05, 'horizontaleNauwkeurigheid': 280427.78, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 1160, 'ritId': '1160', 'lat': 52.000935, 'lng': 4.3594093, 'snelheid': 109.5, 'richting': 342.92, 'horizontaleNauwkeurigheid': 285561.12, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 1169, 'ritId': '1169', 'lat': 52.015755, 'lng': 4.3491635, 'snelheid': 110.9, 'richting': 146.82, 'horizontaleNauwkeurigheid': 287466.66, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 2463, 'ritId': '2463', 'lat': 51.925304, 'lng': 4.4694047, 'snelheid': 0.14, 'richting': 83.49, 'horizontaleNauwkeurigheid': 280272.22, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 2462, 'ritId': '2462', 'lat': 52.357174, 'lng': 4.833952, 'snelheid': 128.65, 'richting': 178.94, 'horizontaleNauwkeurigheid': 280311.12, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 9560, 'ritId': '9560', 'lat': 52.065987, 'lng': 4.5590925, 'snelheid': 191.28, 'richting': 201.99, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 9563, 'ritId': '9563', 'lat': 52.04803, 'lng': 4.5407043, 'snelheid': 179.44, 'richting': 39.11, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 2063, 'ritId': '2063', 'lat': 52.20926, 'lng': 5.9683967, 'snelheid': 0.06, 'richting': 75.092, 'horizontaleNauwkeurigheid': 280311.12, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 867, 'ritId': '867', 'lat': 52.373997, 'lng': 4.930287, 'snelheid': 47.74, 'richting': 121.0, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 762, 'ritId': '762', 'lat': 52.187622, 'lng': 5.311412, 'snelheid': 128.15, 'richting': 319.47, 'horizontaleNauwkeurigheid': 280777.78, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 662, 'ritId': '662', 'lat': 52.14616, 'lng': 5.2668633, 'snelheid': 117.22, 'richting': 263.55, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 864, 'ritId': '864', 'lat': 52.27995, 'lng': 4.677632, 'snelheid': 0.0, 'richting': 280.37, 'horizontaleNauwkeurigheid': 92162540.0, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 863, 'ritId': '863', 'lat': 52.36555, 'lng': 5.768031, 'snelheid': 140.0, 'richting': 51.5748, 'horizontaleNauwkeurigheid': 280505.56, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 766, 'ritId': '766', 'lat': 52.672894, 'lng': 6.1983, 'snelheid': 131.94, 'richting': 168.1185, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 2062, 'ritId': '2062', 'lat': 52.146397, 'lng': 5.3399434, 'snelheid': 119.23, 'richting': 256.142, 'horizontaleNauwkeurigheid': 280233.34, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 859, 'ritId': '859', 'lat': 52.961826, 'lng': 5.9141564, 'snelheid': 0.04, 'richting': 324.374, 'horizontaleNauwkeurigheid': 280388.9, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 2860, 'ritId': '2860', 'lat': 51.96025, 'lng': 4.607625, 'snelheid': 137.08, 'richting': 211.1513, 'horizontaleNauwkeurigheid': 280466.66, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 1768, 'ritId': '1768', 'lat': 52.33337, 'lng': 6.6829834, 'snelheid': 105.76, 'richting': 311.157, 'horizontaleNauwkeurigheid': 280233.34, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 563, 'ritId': '563', 'lat': 52.420765, 'lng': 5.9167185, 'snelheid': 140.14, 'richting': 50.07, 'horizontaleNauwkeurigheid': 280427.78, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 3653, 'ritId': '3653', 'lat': 51.42925, 'lng': 4.243241, 'snelheid': 137.0, 'richting': 262.7617, 'horizontaleNauwkeurigheid': 280272.22, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 2867, 'ritId': '2867', 'lat': 51.95445, 'lng': 4.586915, 'snelheid': 125.91, 'richting': 77.119, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 1763, 'ritId': '1763', 'lat': 52.255764, 'lng': 6.166237, 'snelheid': 37.78, 'richting': 95.367, 'horizontaleNauwkeurigheid': 280350.0, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 3658, 'ritId': '3658', 'lat': 51.73348, 'lng': 5.4304266, 'snelheid': 136.56, 'richting': 64.169, 'horizontaleNauwkeurigheid': 280311.12, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 3165, 'ritId': '3165', 'lat': 52.038662, 'lng': 5.6130085, 'snelheid': 114.28, 'richting': 106.475, 'horizontaleNauwkeurigheid': 280933.34, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 3660, 'ritId': '3660', 'lat': 51.561222, 'lng': 5.077027, 'snelheid': 41.63, 'richting': 100.614, 'horizontaleNauwkeurigheid': 280233.34, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 3666, 'ritId': '3666', 'lat': 51.500744, 'lng': 3.660815, 'snelheid': 72.15, 'richting': 81.919, 'horizontaleNauwkeurigheid': 280116.66, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 3661, 'ritId': '3661', 'lat': 51.891525, 'lng': 5.8572216, 'snelheid': 110.68, 'richting': 177.108, 'horizontaleNauwkeurigheid': 280311.12, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 3659, 'ritId': '3659', 'lat': 51.72432, 'lng': 5.399958, 'snelheid': 140.34, 'richting': 244.2, 'horizontaleNauwkeurigheid': 280155.56, 'type': 'IC', 'bron': 'OBIS'}, {'treinNummer': 3558, 'ritId': '3558', 'lat': 52.028477, 'lng': 4.3336062, 'snelheid': 134.47,

In [9]:
_trains_raw = {
    x.ritId : x.type
    for x in obj.treinen
}
_service_types = Counter(_trains_raw.values())
TrainServiceType = StrEnum('TrainServiceType', ((x.upper(), x) for x in _service_types))

trains_type_by_id: dict[int, TrainServiceType] = {
    int(k) : TrainServiceType(v)
    for k, v in _trains_raw.items()
}

_sorted_ids = sorted(trains_type_by_id.keys())
print(_service_types)
print(f"{ len(_sorted_ids) }: { min(_sorted_ids) } - { max(_sorted_ids) }")

Counter({'IC': 158, 'SPR': 138})
296: 559 - 704364

## Get trip timetables

In [10]:
# JOURNEY DETAILS '/v2/journey' https://apiportal.ns.nl/api-details#api=reisinformatie-api&operation=getJourneyDetail
# payload.productNumbers (string[])
# payload.plannedStock.trainParts[].stockIdentifier (string) # each trainPart has its own destination (see stop)
# payload.plannedStock.trainType (string)
# payload.stops[].stop.UICCode (string)
# payload.stops[].stop.namen.kort/lang/middel (string)
# payload.stops[].arrivals/departures.product.displayName/operatorName

### For single trip

In [11]:
sample_train_id = 9571 #trains_type_by_id.keys().__iter__().__next__()

response = requests.get(NSAPI_URLS['REISINFORMATIE'] + '/api/v2' + '/journey', headers=NS_GET_HEADER,
    params=nsapi.reisinformatie.ApiV2JourneyGetParameters(
        train=sample_train_id, # required when not giving a journey ID
        # dateTime=FOR_DATE, # date only
        omitCrowdForecast=True,
    )
)
obj = nsapi.reisinformatie.RepresentationResponseJourney(**response.json())

class Stop(BaseModel):
    station_uic: int
    name: str
    arrives: AwareDatetime | None
    departs: AwareDatetime | None
class _TrainService0(BaseModel):
    ritnummer: int
    stops: list[Stop]
    categoryCode: str
    categoryName: str
    trainType: str | None
    trainPart_facilities: dict[int, list[str]] | None

def product_from_stops(stops: list[nsapi.reisinformatie.JourneyStop]) -> nsapi.reisinformatie.ProductInterface:
    for stop in stops:
        if stop.departures:
            return stop.departures[0].product
        if stop.arrivals:
            return stop.arrivals[0].product
    raise Exception()

def stock_from_stops(stops: list[nsapi.reisinformatie.JourneyStop]) -> nsapi.reisinformatie.Stock:
    for stop in stops:
        if stop.plannedStock:
            return stop.plannedStock
    return None

def extract_journey_data(ritnummer: int, obj: nsapi.reisinformatie.RepresentationResponseJourney):
    obj.payload.stops = [x for x in obj.payload.stops if x.status != "PASSING"]

    # assert (len(set(int(x) for x in obj.payload.productNumbers)) == 1) # not true
    assert str(ritnummer) in obj.payload.productNumbers

    for stop in obj.payload.stops:
        if len(stop.arrivals) > 1 or len(stop.departures) > 1:
            raise Exception('a')
        is_first_stop: bool = not stop.previousStopId
        is_last_stop: bool = not stop.nextStopId
        if not(is_first_stop or len(stop.arrivals) > 0):
            # raise Exception(f'Ensure requested train timetable is not for a train that has already departed. prevStopId: {stop.previousStopId}')
            pass # we cannot change this circumstance
        # assert (is_last_stop or len(stop.departures) > 0), stop.nextStopId

        for arr_or_depart in chain(stop.arrivals, stop.departures):
            assert(arr_or_depart.plannedTime.utcoffset() == timedelta(hours=2)) # 1 if DST not in effect

    return _TrainService0(
        ritnummer= ritnummer,
        stops= (Stop(
            station_uic = int(x.stop.uicCode),
            name= x.stop.name,
            arrives= x.arrivals[0].plannedTime if x.arrivals else None,
            departs= x.departures[0].plannedTime if x.departures else None,
        )   for x in obj.payload.stops),
        categoryCode= product_from_stops(obj.payload.stops).categoryCode,
        categoryName= product_from_stops(obj.payload.stops).longCategoryName,
        trainType= stock_from_stops(obj.payload.stops).trainType if stock_from_stops(obj.payload.stops) else None,
        trainPart_facilities= {
            int(y.stockIdentifier): y.facilities
            for y in stock_from_stops(obj.payload.stops).trainParts
        }   if stock_from_stops(obj.payload.stops) else None,
    )

sample_train_timetable = extract_journey_data(sample_train_id, obj)
sample_train_timetable

_TrainService0(ritnummer=9571, stops=[Stop(station_uic=8814001, name='Brussel-Zuid', arrives=None, departs=None), Stop(station_uic=8813003, name='Brussel-Centraal', arrives=None, departs=None), Stop(station_uic=8812005, name='Brussel-Noord', arrives=None, departs=None), Stop(station_uic=8822004, name='Mechelen', arrives=None, departs=None), Stop(station_uic=8821121, name='Antwerpen-Berchem', arrives=None, departs=None), Stop(station_uic=8821006, name='Antwerpen-Centraal', arrives=None, departs=None), Stop(station_uic=8821063, name='Antwerpen-Luchtbal', arrives=None, departs=None), Stop(station_uic=8821105, name='Noorderkempen', arrives=None, departs=None), Stop(station_uic=8400542, name='Rotterdam Lombardijen', arrives=None, departs=None), Stop(station_uic=8400534, name='Rotterdam Stadion', arrives=None, departs=None), Stop(station_uic=8400533, name='Rotterdam Zuid', arrives=None, departs=None), Stop(station_uic=8400529, name='Rotterdam Blaak', arrives=None, departs=None), Stop(station_uic=8400530, name='Rotterdam Centraal', arrives=datetime.datetime(2026, 8, 10, 20, 17, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 20, 21, tzinfo=TzInfo(7200))), Stop(station_uic=8400332, name='Hoofddorp', arrives=None, departs=None), Stop(station_uic=8400561, name='Schiphol Airport', arrives=datetime.datetime(2026, 8, 10, 20, 47, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 20, 49, tzinfo=TzInfo(7200))), Stop(station_uic=8400061, name='Amsterdam Zuid', arrives=datetime.datetime(2026, 8, 10, 20, 55, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 20, 57, tzinfo=TzInfo(7200))), Stop(station_uic=8400056, name='Amsterdam RAI', arrives=None, departs=None), Stop(station_uic=8400194, name='Duivendrecht', arrives=None, departs=None), Stop(station_uic=8400163, name='Diemen Zuid', arrives=None, departs=None)], categoryCode='ECD', categoryName='Eurocity Direct', trainType=None, trainPart_facilities=None)

### For all known train trips

In [12]:
journeys_raw_pkl = raw_out_dir / 'journey_details_raw.pkl'
journeys_pkl = raw_out_dir / 'journey_details.pkl'

def _journey_api_request(train_id: int) -> dict[str, Any]:
    response = requests.get(NSAPI_URLS['REISINFORMATIE'] + '/api/v2' + '/journey', headers=NS_GET_HEADER,
        params=nsapi.reisinformatie.ApiV2JourneyGetParameters(
            train=train_id, # required when not giving a journey ID
            omitCrowdForecast=True,
        )
    )
    return response.json()
def _get_journey_raw_obj() -> dict[str, dict[str, Any]]:
    if not journeys_raw_pkl.exists():
        train_ids = trains_type_by_id.keys()
        raw_obj = {
            train_id : _journey_api_request(train_id)
            for train_id in tqdm(train_ids)
        }
        with open(journeys_raw_pkl, 'wb') as file:
            pickle.dump(raw_obj, file, protocol=-1)
    else:
        with open(journeys_raw_pkl, 'rb') as file:
            raw_obj = pickle.load(file)
    return raw_obj
def _get_journey_obj() -> dict[int, nsapi.reisinformatie.RepresentationResponseJourney]:
    '''May not contain all requested train_ids; some will not be found.'''
    if not journeys_pkl.exists():
        raw_obj = _get_journey_raw_obj()
        obj = dict[int, nsapi.reisinformatie.RepresentationResponseJourney]()
        for k, v in raw_obj.items():
            if (v.get('code', 200) == 404):
                continue
            obj |= {
                k : nsapi.reisinformatie.RepresentationResponseJourney(**v)
            }

        with open(journeys_pkl, 'wb') as file:
            pickle.dump(obj, file, protocol=-1)
    else:
        with open(journeys_pkl, 'rb') as file:
            obj = pickle.load(file)
    return obj

obj = _get_journey_obj()

_trains_timetables: dict[int, _TrainService0] = {
    train_id : extract_journey_data(train_id, journey_obj)
    for train_id, journey_obj in obj.items()
}

_trains_timetables

  0%|          | 0/296 [00:00<?, ?it/s]

  0%|          | 1/296 [00:00<04:09,  1.18it/s]

  1%|          | 2/296 [00:01<03:47,  1.29it/s]

  1%|          | 3/296 [00:02<04:03,  1.20it/s]

  1%|▏         | 4/296 [00:02<03:14,  1.50it/s]

  2%|▏         | 5/296 [00:03<03:33,  1.37it/s]

  2%|▏         | 6/296 [00:04<03:39,  1.32it/s]

  2%|▏         | 7/296 [00:05<03:43,  1.30it/s]

  3%|▎         | 8/296 [00:06<03:45,  1.28it/s]

  3%|▎         | 9/296 [00:06<03:47,  1.26it/s]

  3%|▎         | 10/296 [00:07<03:42,  1.28it/s]

  4%|▎         | 11/296 [00:08<03:39,  1.30it/s]

  4%|▍         | 12/296 [00:09<03:40,  1.29it/s]

  4%|▍         | 13/296 [00:09<03:34,  1.32it/s]

  5%|▍         | 14/296 [00:10<03:35,  1.31it/s]

  5%|▌         | 15/296 [00:11<03:36,  1.30it/s]

  5%|▌         | 16/296 [00:12<03:35,  1.30it/s]

  6%|▌         | 17/296 [00:12<03:24,  1.36it/s]

  6%|▌         | 18/296 [00:13<03:28,  1.33it/s]

  6%|▋         | 19/296 [00:14<03:31,  1.31it/s]

  7%|▋         | 20/296 [00:15<03:18,  1.39it/s]

  7%|▋         | 21/296 [00:16<03:34,  1.28it/s]

  7%|▋         | 22/296 [00:16<03:28,  1.31it/s]

  8%|▊         | 23/296 [00:17<03:23,  1.34it/s]

  8%|▊         | 24/296 [00:18<03:14,  1.40it/s]

  8%|▊         | 25/296 [00:19<03:30,  1.29it/s]

  9%|▉         | 26/296 [00:19<03:37,  1.24it/s]

  9%|▉         | 27/296 [00:20<03:29,  1.28it/s]

  9%|▉         | 28/296 [00:21<03:21,  1.33it/s]

 10%|▉         | 29/296 [00:22<03:16,  1.36it/s]

 10%|█         | 30/296 [00:22<03:20,  1.33it/s]

 10%|█         | 31/296 [00:23<03:07,  1.41it/s]

 11%|█         | 32/296 [00:24<03:16,  1.34it/s]

 11%|█         | 33/296 [00:24<03:10,  1.38it/s]

 11%|█▏        | 34/296 [00:25<02:48,  1.55it/s]

 12%|█▏        | 35/296 [00:26<02:48,  1.55it/s]

 12%|█▏        | 36/296 [00:26<02:49,  1.53it/s]

 12%|█▎        | 37/296 [00:27<03:18,  1.30it/s]

 13%|█▎        | 38/296 [00:28<03:27,  1.25it/s]

 13%|█▎        | 39/296 [00:29<03:33,  1.20it/s]

 14%|█▎        | 40/296 [00:30<03:30,  1.22it/s]

 14%|█▍        | 41/296 [00:31<03:29,  1.22it/s]

 14%|█▍        | 42/296 [00:32<03:34,  1.18it/s]

 15%|█▍        | 43/296 [00:33<03:44,  1.13it/s]

 15%|█▍        | 44/296 [00:35<06:07,  1.46s/it]

 15%|█▌        | 45/296 [00:36<05:12,  1.25s/it]

 16%|█▌        | 46/296 [00:37<04:35,  1.10s/it]

 16%|█▌        | 47/296 [00:38<04:08,  1.00it/s]

 16%|█▌        | 48/296 [00:38<03:50,  1.08it/s]

 17%|█▋        | 49/296 [00:39<03:29,  1.18it/s]

 17%|█▋        | 50/296 [00:40<03:14,  1.26it/s]

 17%|█▋        | 51/296 [00:40<03:02,  1.34it/s]

 18%|█▊        | 52/296 [00:42<04:08,  1.02s/it]

 18%|█▊        | 53/296 [00:43<03:37,  1.12it/s]

 18%|█▊        | 54/296 [00:43<03:17,  1.23it/s]

 19%|█▊        | 55/296 [00:44<03:08,  1.28it/s]

 19%|█▉        | 56/296 [00:45<02:58,  1.34it/s]

 19%|█▉        | 57/296 [00:45<02:50,  1.40it/s]

 20%|█▉        | 58/296 [00:46<02:51,  1.39it/s]

 20%|█▉        | 59/296 [00:47<02:48,  1.41it/s]

 20%|██        | 60/296 [00:47<02:45,  1.43it/s]

 21%|██        | 61/296 [00:48<02:41,  1.45it/s]

 21%|██        | 62/296 [00:49<02:35,  1.50it/s]

 21%|██▏       | 63/296 [00:50<02:54,  1.34it/s]

 22%|██▏       | 64/296 [00:50<02:49,  1.37it/s]

 22%|██▏       | 65/296 [00:51<02:45,  1.40it/s]

 22%|██▏       | 66/296 [00:52<02:39,  1.44it/s]

 23%|██▎       | 67/296 [00:52<02:37,  1.45it/s]

 23%|██▎       | 68/296 [00:53<02:35,  1.47it/s]

 23%|██▎       | 69/296 [00:54<02:34,  1.47it/s]

 24%|██▎       | 70/296 [00:54<02:37,  1.43it/s]

 24%|██▍       | 71/296 [00:55<02:46,  1.35it/s]

 24%|██▍       | 72/296 [00:56<02:40,  1.40it/s]

 25%|██▍       | 73/296 [00:56<02:33,  1.45it/s]

 25%|██▌       | 74/296 [00:57<02:35,  1.43it/s]

 25%|██▌       | 75/296 [00:58<02:34,  1.43it/s]

 26%|██▌       | 76/296 [01:02<06:53,  1.88s/it]

 26%|██▌       | 77/296 [01:04<05:54,  1.62s/it]

 26%|██▋       | 78/296 [01:04<05:06,  1.41s/it]

 27%|██▋       | 79/296 [01:05<04:15,  1.18s/it]

 27%|██▋       | 80/296 [01:06<03:41,  1.03s/it]

 27%|██▋       | 81/296 [01:06<02:58,  1.21it/s]

 28%|██▊       | 82/296 [01:07<02:54,  1.23it/s]

 28%|██▊       | 83/296 [01:07<02:41,  1.32it/s]

 28%|██▊       | 84/296 [01:08<02:33,  1.38it/s]

 29%|██▊       | 85/296 [01:09<02:26,  1.44it/s]

 29%|██▉       | 86/296 [01:10<02:47,  1.26it/s]

 29%|██▉       | 87/296 [01:10<02:36,  1.34it/s]

 30%|██▉       | 88/296 [01:11<02:31,  1.37it/s]

 30%|███       | 89/296 [01:12<02:36,  1.33it/s]

 30%|███       | 90/296 [01:12<02:17,  1.50it/s]

 31%|███       | 91/296 [01:13<01:58,  1.74it/s]

 31%|███       | 92/296 [01:13<02:04,  1.63it/s]

 31%|███▏      | 93/296 [01:14<02:14,  1.51it/s]

 32%|███▏      | 94/296 [01:15<02:18,  1.46it/s]

 32%|███▏      | 95/296 [01:15<02:06,  1.59it/s]

 32%|███▏      | 96/296 [01:16<02:09,  1.54it/s]

 33%|███▎      | 97/296 [01:17<02:08,  1.55it/s]

 33%|███▎      | 98/296 [01:17<01:55,  1.71it/s]

 33%|███▎      | 99/296 [01:18<02:02,  1.61it/s]

 34%|███▍      | 100/296 [01:19<02:09,  1.51it/s]

 34%|███▍      | 101/296 [01:19<02:06,  1.55it/s]

 34%|███▍      | 102/296 [01:20<02:18,  1.40it/s]

 35%|███▍      | 103/296 [01:21<02:16,  1.41it/s]

 35%|███▌      | 104/296 [01:22<02:15,  1.42it/s]

 35%|███▌      | 105/296 [01:22<02:13,  1.43it/s]

 36%|███▌      | 106/296 [01:23<02:14,  1.41it/s]

 36%|███▌      | 107/296 [01:24<02:13,  1.41it/s]

 36%|███▋      | 108/296 [01:24<02:11,  1.43it/s]

 37%|███▋      | 109/296 [01:25<02:11,  1.42it/s]

 37%|███▋      | 110/296 [01:26<02:09,  1.43it/s]

 38%|███▊      | 111/296 [01:26<02:03,  1.50it/s]

 38%|███▊      | 112/296 [01:27<02:04,  1.47it/s]

 38%|███▊      | 113/296 [01:28<02:08,  1.42it/s]

 39%|███▊      | 114/296 [01:28<02:05,  1.45it/s]

 39%|███▉      | 115/296 [01:29<02:10,  1.38it/s]

 39%|███▉      | 116/296 [01:30<02:12,  1.36it/s]

 40%|███▉      | 117/296 [01:31<02:10,  1.37it/s]

 40%|███▉      | 118/296 [01:32<02:10,  1.36it/s]

 40%|████      | 119/296 [01:32<02:07,  1.39it/s]

 41%|████      | 120/296 [01:33<02:05,  1.40it/s]

 41%|████      | 121/296 [01:34<02:06,  1.39it/s]

 41%|████      | 122/296 [01:34<02:01,  1.43it/s]

 42%|████▏     | 123/296 [01:35<02:04,  1.39it/s]

 42%|████▏     | 124/296 [01:36<02:00,  1.43it/s]

 42%|████▏     | 125/296 [01:36<01:55,  1.48it/s]

 43%|████▎     | 126/296 [01:37<01:58,  1.44it/s]

 43%|████▎     | 127/296 [01:38<01:46,  1.59it/s]

 43%|████▎     | 128/296 [01:38<01:50,  1.52it/s]

 44%|████▎     | 129/296 [01:39<01:48,  1.54it/s]

 44%|████▍     | 130/296 [01:40<01:49,  1.52it/s]

 44%|████▍     | 131/296 [01:40<01:54,  1.45it/s]

 45%|████▍     | 132/296 [01:43<03:31,  1.29s/it]

 45%|████▍     | 133/296 [01:46<04:41,  1.72s/it]

 45%|████▌     | 134/296 [01:46<03:47,  1.40s/it]

 46%|████▌     | 135/296 [01:47<03:08,  1.17s/it]

 46%|████▌     | 136/296 [01:48<02:35,  1.03it/s]

 46%|████▋     | 137/296 [01:48<02:17,  1.16it/s]

 47%|████▋     | 138/296 [01:49<02:20,  1.13it/s]

 47%|████▋     | 139/296 [01:50<01:57,  1.33it/s]

 47%|████▋     | 140/296 [01:50<01:54,  1.36it/s]

 48%|████▊     | 141/296 [01:51<01:42,  1.51it/s]

 48%|████▊     | 142/296 [01:51<01:43,  1.49it/s]

 48%|████▊     | 143/296 [01:52<01:43,  1.48it/s]

 49%|████▊     | 144/296 [01:53<01:31,  1.66it/s]

 49%|████▉     | 145/296 [01:53<01:35,  1.58it/s]

 49%|████▉     | 146/296 [01:54<01:47,  1.39it/s]

 50%|████▉     | 147/296 [01:55<01:49,  1.36it/s]

 50%|█████     | 148/296 [01:56<02:02,  1.21it/s]

 50%|█████     | 149/296 [01:57<01:59,  1.23it/s]

 51%|█████     | 150/296 [01:58<01:58,  1.23it/s]

 51%|█████     | 151/296 [01:58<01:59,  1.21it/s]

 51%|█████▏    | 152/296 [01:59<01:52,  1.28it/s]

 52%|█████▏    | 153/296 [02:00<01:54,  1.25it/s]

 52%|█████▏    | 154/296 [02:01<01:54,  1.24it/s]

 52%|█████▏    | 155/296 [02:01<01:47,  1.31it/s]

 53%|█████▎    | 156/296 [02:02<01:35,  1.46it/s]

 53%|█████▎    | 157/296 [02:03<01:34,  1.48it/s]

 53%|█████▎    | 158/296 [02:04<02:10,  1.06it/s]

 54%|█████▎    | 159/296 [02:05<01:59,  1.14it/s]

 54%|█████▍    | 160/296 [02:06<01:52,  1.21it/s]

 54%|█████▍    | 161/296 [02:06<01:35,  1.41it/s]

 55%|█████▍    | 162/296 [02:07<01:34,  1.42it/s]

 55%|█████▌    | 163/296 [02:07<01:34,  1.41it/s]

 55%|█████▌    | 164/296 [02:08<01:38,  1.34it/s]

 56%|█████▌    | 165/296 [02:09<01:40,  1.31it/s]

 56%|█████▌    | 166/296 [02:10<01:42,  1.27it/s]

 56%|█████▋    | 167/296 [02:11<01:40,  1.28it/s]

 57%|█████▋    | 168/296 [02:11<01:36,  1.32it/s]

 57%|█████▋    | 169/296 [02:12<01:47,  1.18it/s]

 57%|█████▋    | 170/296 [02:13<01:39,  1.26it/s]

 58%|█████▊    | 171/296 [02:14<01:39,  1.26it/s]

 58%|█████▊    | 172/296 [02:14<01:24,  1.47it/s]

 58%|█████▊    | 173/296 [02:15<01:28,  1.38it/s]

 59%|█████▉    | 174/296 [02:16<01:31,  1.34it/s]

 59%|█████▉    | 175/296 [02:17<01:33,  1.29it/s]

 59%|█████▉    | 176/296 [02:18<01:32,  1.29it/s]

 60%|█████▉    | 177/296 [02:18<01:29,  1.33it/s]

 60%|██████    | 178/296 [02:19<01:40,  1.18it/s]

 60%|██████    | 179/296 [02:20<01:40,  1.17it/s]

 61%|██████    | 180/296 [02:21<01:34,  1.23it/s]

 61%|██████    | 181/296 [02:22<01:27,  1.31it/s]

 61%|██████▏   | 182/296 [02:22<01:21,  1.39it/s]

 62%|██████▏   | 183/296 [02:23<01:19,  1.43it/s]

 62%|██████▏   | 184/296 [02:24<01:24,  1.33it/s]

 62%|██████▎   | 185/296 [02:24<01:21,  1.36it/s]

 63%|██████▎   | 186/296 [02:25<01:19,  1.39it/s]

 63%|██████▎   | 187/296 [02:26<01:15,  1.45it/s]

 64%|██████▎   | 188/296 [02:26<01:12,  1.50it/s]

 64%|██████▍   | 189/296 [02:27<01:13,  1.46it/s]

 64%|██████▍   | 190/296 [02:28<01:16,  1.39it/s]

 65%|██████▍   | 191/296 [02:29<01:14,  1.41it/s]

 65%|██████▍   | 192/296 [02:29<01:11,  1.46it/s]

 65%|██████▌   | 193/296 [02:30<01:12,  1.41it/s]

 66%|██████▌   | 194/296 [02:31<01:11,  1.42it/s]

 66%|██████▌   | 195/296 [02:31<01:11,  1.41it/s]

 66%|██████▌   | 196/296 [02:32<01:10,  1.41it/s]

 67%|██████▋   | 197/296 [02:33<01:09,  1.42it/s]

 67%|██████▋   | 198/296 [02:33<01:06,  1.48it/s]

 67%|██████▋   | 199/296 [02:34<01:09,  1.40it/s]

 68%|██████▊   | 200/296 [02:35<01:11,  1.33it/s]

 68%|██████▊   | 201/296 [02:36<01:16,  1.23it/s]

 68%|██████▊   | 202/296 [02:37<01:14,  1.27it/s]

 69%|██████▊   | 203/296 [02:37<01:10,  1.32it/s]

 69%|██████▉   | 204/296 [02:38<01:08,  1.35it/s]

 69%|██████▉   | 205/296 [02:39<01:08,  1.33it/s]

 70%|██████▉   | 206/296 [02:40<01:06,  1.35it/s]

 70%|██████▉   | 207/296 [02:40<01:07,  1.32it/s]

 70%|███████   | 208/296 [02:41<01:04,  1.35it/s]

 71%|███████   | 209/296 [02:42<01:03,  1.38it/s]

 71%|███████   | 210/296 [02:42<01:02,  1.39it/s]

 71%|███████▏  | 211/296 [02:43<01:01,  1.39it/s]

 72%|███████▏  | 212/296 [02:44<01:06,  1.26it/s]

 72%|███████▏  | 213/296 [02:45<01:03,  1.30it/s]

 72%|███████▏  | 214/296 [02:46<01:01,  1.34it/s]

 73%|███████▎  | 215/296 [02:47<01:06,  1.23it/s]

 73%|███████▎  | 216/296 [02:47<01:04,  1.25it/s]

 73%|███████▎  | 217/296 [02:48<01:07,  1.18it/s]

 74%|███████▎  | 218/296 [02:49<01:02,  1.25it/s]

 74%|███████▍  | 219/296 [02:50<00:58,  1.31it/s]

 74%|███████▍  | 220/296 [02:50<00:56,  1.36it/s]

 75%|███████▍  | 221/296 [02:51<01:02,  1.20it/s]

 75%|███████▌  | 222/296 [02:52<00:59,  1.24it/s]

 75%|███████▌  | 223/296 [02:53<00:58,  1.24it/s]

 76%|███████▌  | 224/296 [02:54<00:57,  1.24it/s]

 76%|███████▌  | 225/296 [02:54<00:55,  1.27it/s]

 76%|███████▋  | 226/296 [02:55<00:53,  1.31it/s]

 77%|███████▋  | 227/296 [02:56<00:52,  1.31it/s]

 77%|███████▋  | 228/296 [02:57<00:50,  1.34it/s]

 77%|███████▋  | 229/296 [02:57<00:48,  1.39it/s]

 78%|███████▊  | 230/296 [02:58<00:48,  1.36it/s]

 78%|███████▊  | 231/296 [02:59<00:47,  1.36it/s]

 78%|███████▊  | 232/296 [03:00<00:48,  1.31it/s]

 79%|███████▊  | 233/296 [03:00<00:49,  1.28it/s]

 79%|███████▉  | 234/296 [03:01<00:46,  1.33it/s]

 79%|███████▉  | 235/296 [03:02<00:46,  1.31it/s]

 80%|███████▉  | 236/296 [03:03<00:46,  1.29it/s]

 80%|████████  | 237/296 [03:04<00:45,  1.29it/s]

 80%|████████  | 238/296 [03:04<00:45,  1.27it/s]

 81%|████████  | 239/296 [03:05<00:46,  1.23it/s]

 81%|████████  | 240/296 [03:06<00:45,  1.24it/s]

 81%|████████▏ | 241/296 [03:07<00:44,  1.24it/s]

 82%|████████▏ | 242/296 [03:08<00:43,  1.25it/s]

 82%|████████▏ | 243/296 [03:09<00:46,  1.13it/s]

 82%|████████▏ | 244/296 [03:10<00:45,  1.15it/s]

 83%|████████▎ | 245/296 [03:10<00:38,  1.32it/s]

 83%|████████▎ | 246/296 [03:11<00:38,  1.31it/s]

 83%|████████▎ | 247/296 [03:12<00:37,  1.29it/s]

 84%|████████▍ | 248/296 [03:12<00:36,  1.30it/s]

 84%|████████▍ | 249/296 [03:13<00:37,  1.26it/s]

 84%|████████▍ | 250/296 [03:14<00:35,  1.31it/s]

 85%|████████▍ | 251/296 [03:14<00:32,  1.40it/s]

 85%|████████▌ | 252/296 [03:15<00:31,  1.39it/s]

 85%|████████▌ | 253/296 [03:16<00:31,  1.34it/s]

 86%|████████▌ | 254/296 [03:17<00:30,  1.38it/s]

 86%|████████▌ | 255/296 [03:17<00:29,  1.41it/s]

 86%|████████▋ | 256/296 [03:18<00:27,  1.46it/s]

 87%|████████▋ | 257/296 [03:19<00:26,  1.46it/s]

 87%|████████▋ | 258/296 [03:19<00:25,  1.49it/s]

 88%|████████▊ | 259/296 [03:20<00:26,  1.40it/s]

 88%|████████▊ | 260/296 [03:21<00:24,  1.47it/s]

 88%|████████▊ | 261/296 [03:21<00:21,  1.62it/s]

 89%|████████▊ | 262/296 [03:22<00:24,  1.39it/s]

 89%|████████▉ | 263/296 [03:23<00:24,  1.34it/s]

 89%|████████▉ | 264/296 [03:24<00:24,  1.30it/s]

 90%|████████▉ | 265/296 [03:24<00:23,  1.34it/s]

 90%|████████▉ | 266/296 [03:25<00:22,  1.32it/s]

 90%|█████████ | 267/296 [03:26<00:23,  1.25it/s]

 91%|█████████ | 268/296 [03:27<00:23,  1.19it/s]

 91%|█████████ | 269/296 [03:28<00:21,  1.25it/s]

 91%|█████████ | 270/296 [03:29<00:20,  1.25it/s]

 92%|█████████▏| 271/296 [03:29<00:19,  1.28it/s]

 92%|█████████▏| 272/296 [03:30<00:18,  1.27it/s]

 92%|█████████▏| 273/296 [03:31<00:17,  1.31it/s]

 93%|█████████▎| 274/296 [03:32<00:16,  1.31it/s]

 93%|█████████▎| 275/296 [03:32<00:15,  1.32it/s]

 93%|█████████▎| 276/296 [03:34<00:17,  1.12it/s]

 94%|█████████▎| 277/296 [03:34<00:16,  1.17it/s]

 94%|█████████▍| 278/296 [03:35<00:14,  1.20it/s]

 94%|█████████▍| 279/296 [03:36<00:13,  1.23it/s]

 95%|█████████▍| 280/296 [03:37<00:12,  1.27it/s]

 95%|█████████▍| 281/296 [03:37<00:12,  1.24it/s]

 95%|█████████▌| 282/296 [03:39<00:12,  1.13it/s]

 96%|█████████▌| 283/296 [03:39<00:10,  1.19it/s]

 96%|█████████▌| 284/296 [03:40<00:08,  1.36it/s]

 96%|█████████▋| 285/296 [03:40<00:07,  1.40it/s]

 97%|█████████▋| 286/296 [03:41<00:07,  1.37it/s]

 97%|█████████▋| 287/296 [03:42<00:06,  1.37it/s]

 97%|█████████▋| 288/296 [03:43<00:05,  1.38it/s]

 98%|█████████▊| 289/296 [03:43<00:04,  1.40it/s]

 98%|█████████▊| 290/296 [03:44<00:04,  1.39it/s]

 98%|█████████▊| 291/296 [03:45<00:03,  1.42it/s]

 99%|█████████▊| 292/296 [03:45<00:02,  1.45it/s]

 99%|█████████▉| 293/296 [03:46<00:02,  1.32it/s]

 99%|█████████▉| 294/296 [03:47<00:01,  1.34it/s]

100%|█████████▉| 295/296 [03:48<00:00,  1.33it/s]

100%|██████████| 296/296 [03:48<00:00,  1.44it/s]

100%|██████████| 296/296 [03:48<00:00,  1.29it/s]

{8758: _TrainService0(ritnummer=8758, stops=[Stop(station_uic=8400258, name='Gouda', arrives=None, departs=datetime.datetime(2026, 8, 10, 18, 13, tzinfo=TzInfo(7200))), Stop(station_uic=8400677, name='Waddinxveen Triangel', arrives=datetime.datetime(2026, 8, 10, 18, 19, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 19, tzinfo=TzInfo(7200))), Stop(station_uic=8400675, name='Waddinxveen', arrives=datetime.datetime(2026, 8, 10, 18, 21, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 23, tzinfo=TzInfo(7200))), Stop(station_uic=8400674, name='Waddinxveen Noord', arrives=datetime.datetime(2026, 8, 10, 18, 25, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 25, tzinfo=TzInfo(7200))), Stop(station_uic=8400126, name='Boskoop Snijdelwijk', arrives=datetime.datetime(2026, 8, 10, 18, 27, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 27, tzinfo=TzInfo(7200))), Stop(station_uic=8400125, name='Boskoop', arrives=datetime.datetime(2026, 8, 10, 18, 29, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 30, tzinfo=TzInfo(7200))), Stop(station_uic=8400053, name='Alphen a/d Rijn', arrives=datetime.datetime(2026, 8, 10, 18, 35, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2013: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 6461: _TrainService0(ritnummer=6461, stops=[Stop(station_uic=8400594, name='Tilburg Universiteit', arrives=None, departs=datetime.datetime(2026, 8, 10, 17, 34, tzinfo=TzInfo(7200))), Stop(station_uic=8400597, name='Tilburg', arrives=datetime.datetime(2026, 8, 10, 17, 38, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 17, 39, tzinfo=TzInfo(7200))), Stop(station_uic=8400482, name='Oisterwijk', arrives=datetime.datetime(2026, 8, 10, 17, 45, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 17, 45, tzinfo=TzInfo(7200))), Stop(station_uic=8400129, name='Boxtel', arrives=datetime.datetime(2026, 8, 10, 17, 52, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 17, 53, tzinfo=TzInfo(7200))), Stop(station_uic=8400112, name='Best', arrives=datetime.datetime(2026, 8, 10, 17, 59, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 17, 59, tzinfo=TzInfo(7200))), Stop(station_uic=8400196, name='Eindhoven Strijp-S', arrives=datetime.datetime(2026, 8, 10, 18, 5, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 5, tzinfo=TzInfo(7200))), Stop(station_uic=8400206, name='Eindhoven Centraal', arrives=datetime.datetime(2026, 8, 10, 18, 9, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 17, tzinfo=TzInfo(7200))), Stop(station_uic=8400245, name='Geldrop', arrives=datetime.datetime(2026, 8, 10, 18, 22, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 22, tzinfo=TzInfo(7200))), Stop(station_uic=8400308, name='Heeze', arrives=datetime.datetime(2026, 8, 10, 18, 26, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 26, tzinfo=TzInfo(7200))), Stop(station_uic=8400432, name='Maarheeze', arrives=datetime.datetime(2026, 8, 10, 18, 33, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 33, tzinfo=TzInfo(7200))), Stop(station_uic=8400684, name='Weert', arrives=datetime.datetime(2026, 8, 10, 18, 40, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2210: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 6561: _TrainService0(ritnummer=6561, stops=[Stop(station_uic=8400319, name="'s-Hertogenbosch", arrives=None, departs=datetime.datetime(2026, 8, 10, 17, 28, tzinfo=TzInfo(7200))), Stop(station_uic=8400667, name='Vught', arrives=datetime.datetime(2026, 8, 10, 17, 33, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 17, 33, tzinfo=TzInfo(7200))), Stop(station_uic=8400129, name='Boxtel', arrives=datetime.datetime(2026, 8, 10, 17, 39, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 17, 39, tzinfo=TzInfo(7200))), Stop(station_uic=8400112, name='Best', arrives=datetime.datetime(2026, 8, 10, 17, 45, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 17, 45, tzinfo=TzInfo(7200))), Stop(station_uic=8400196, name='Eindhoven Strijp-S', arrives=datetime.datetime(2026, 8, 10, 17, 51, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 17, 51, tzinfo=TzInfo(7200))), Stop(station_uic=8400206, name='Eindhoven Centraal', arrives=datetime.datetime(2026, 8, 10, 17, 55, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 7, tzinfo=TzInfo(7200))), Stop(station_uic=8400242, name='Helmond Brandevoort', arrives=datetime.datetime(2026, 8, 10, 18, 13, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 13, tzinfo=TzInfo(7200))), Stop(station_uic=8400300, name="Helmond 't Hout", arrives=datetime.datetime(2026, 8, 10, 18, 16, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 16, tzinfo=TzInfo(7200))), Stop(station_uic=8400313, name='Helmond', arrives=datetime.datetime(2026, 8, 10, 18, 20, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 20, tzinfo=TzInfo(7200))), Stop(station_uic=8400299, name='Helmond Brouwhuis', arrives=datetime.datetime(2026, 8, 10, 18, 23, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 23, tzinfo=TzInfo(7200))), Stop(station_uic=8400172, name='Deurne', arrives=datetime.datetime(2026, 8, 10, 18, 28, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2212: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI'], 2208: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 6669: _TrainService0(ritnummer=6669, stops=[Stop(station_uic=8400071, name='Arnhem Centraal', arrives=None, departs=datetime.datetime(2026, 8, 10, 18, 27, tzinfo=TzInfo(7200))), Stop(station_uic=8400227, name='Arnhem Zuid', arrives=datetime.datetime(2026, 8, 10, 18, 32, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 32, tzinfo=TzInfo(7200))), Stop(station_uic=8400207, name='Elst', arrives=datetime.datetime(2026, 8, 10, 18, 36, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 36, tzinfo=TzInfo(7200))), Stop(station_uic=8400451, name='Nijmegen Lent', arrives=datetime.datetime(2026, 8, 10, 18, 40, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 40, tzinfo=TzInfo(7200))), Stop(station_uic=8400470, name='Nijmegen', arrives=datetime.datetime(2026, 8, 10, 18, 45, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 48, tzinfo=TzInfo(7200))), Stop(station_uic=8400477, name='Nijmegen Goffert', arrives=datetime.datetime(2026, 8, 10, 18, 51, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 51, tzinfo=TzInfo(7200))), Stop(station_uic=8400475, name='Nijmegen Dukenburg', arrives=datetime.datetime(2026, 8, 10, 18, 54, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 54, tzinfo=TzInfo(7200))), Stop(station_uic=8400710, name='Wijchen', arrives=datetime.datetime(2026, 8, 10, 18, 58, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 58, tzinfo=TzInfo(7200))), Stop(station_uic=8400515, name='Ravenstein', arrives=datetime.datetime(2026, 8, 10, 19, 4, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 4, tzinfo=TzInfo(7200))), Stop(station_uic=8400495, name='Oss', arrives=datetime.datetime(2026, 8, 10, 19, 10, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 10, tzinfo=TzInfo(7200))), Stop(station_uic=8400496, name='Oss West', arrives=datetime.datetime(2026, 8, 10, 19, 13, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 13, tzinfo=TzInfo(7200))), Stop(station_uic=8400524, name='Rosmalen', arrives=datetime.datetime(2026, 8, 10, 19, 20, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 20, tzinfo=TzInfo(7200))), Stop(station_uic=8400320, name="'s-Hertogenbosch Oost", arrives=datetime.datetime(2026, 8, 10, 19, 24, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 24, tzinfo=TzInfo(7200))), Stop(station_uic=8400319, name="'s-Hertogenbosch", arrives=datetime.datetime(2026, 8, 10, 19, 28, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 31, tzinfo=TzInfo(7200))), Stop(station_uic=8400597, name='Tilburg', arrives=datetime.datetime(2026, 8, 10, 19, 45, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 47, tzinfo=TzInfo(7200))), Stop(station_uic=8400594, name='Tilburg Universiteit', arrives=datetime.datetime(2026, 8, 10, 19, 50, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 50, tzinfo=TzInfo(7200))), Stop(station_uic=8400598, name='Tilburg Reeshof', arrives=datetime.datetime(2026, 8, 10, 19, 54, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 54, tzinfo=TzInfo(7200))), Stop(station_uic=8400251, name='Gilze-Rijen', arrives=datetime.datetime(2026, 8, 10, 19, 58, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 58, tzinfo=TzInfo(7200))), Stop(station_uic=8400131, name='Breda', arrives=datetime.datetime(2026, 8, 10, 20, 5, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 20, 9, tzinfo=TzInfo(7200))), Stop(station_uic=8400132, name='Breda-Prinsenbeek', arrives=datetime.datetime(2026, 8, 10, 20, 13, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 20, 13, tzinfo=TzInfo(7200))), Stop(station_uic=8400382, name='Lage Zwaluwe', arrives=datetime.datetime(2026, 8, 10, 20, 20, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 20, 20, tzinfo=TzInfo(7200))), Stop(station_uic=8400181, name='Dordrecht Zuid', arrives=datetime.datetime(2026, 8, 10, 20, 28, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 20, 28, tzinfo=TzInfo(7200))), Stop(station_uic=8400180, name='Dordrecht', arrives=datetime.datetime(2026, 8, 10, 20, 32, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2221: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 7663: _TrainService0(ritnummer=7663, stops=[Stop(station_uic=8400710, name='Wijchen', arrives=None, departs=datetime.datetime(2026, 8, 10, 17, 48, tzinfo=TzInfo(7200))), Stop(station_uic=8400475, name='Nijmegen Dukenburg', arrives=datetime.datetime(2026, 8, 10, 17, 52, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 17, 52, tzinfo=TzInfo(7200))), Stop(station_uic=8400477, name='Nijmegen Goffert', arrives=datetime.datetime(2026, 8, 10, 17, 55, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 17, 55, tzinfo=TzInfo(7200))), Stop(station_uic=8400470, name='Nijmegen', arrives=datetime.datetime(2026, 8, 10, 17, 59, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 2, tzinfo=TzInfo(7200))), Stop(station_uic=8400451, name='Nijmegen Lent', arrives=datetime.datetime(2026, 8, 10, 18, 5, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 5, tzinfo=TzInfo(7200))), Stop(station_uic=8400207, name='Elst', arrives=datetime.datetime(2026, 8, 10, 18, 10, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 10, tzinfo=TzInfo(7200))), Stop(station_uic=8400227, name='Arnhem Zuid', arrives=datetime.datetime(2026, 8, 10, 18, 14, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 14, tzinfo=TzInfo(7200))), Stop(station_uic=8400071, name='Arnhem Centraal', arrives=datetime.datetime(2026, 8, 10, 18, 19, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 25, tzinfo=TzInfo(7200))), Stop(station_uic=8400072, name='Arnhem Velperpoort', arrives=datetime.datetime(2026, 8, 10, 18, 27, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 27, tzinfo=TzInfo(7200))), Stop(station_uic=8400075, name='Arnhem Presikhaaf', arrives=datetime.datetime(2026, 8, 10, 18, 31, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 31, tzinfo=TzInfo(7200))), Stop(station_uic=8400640, name='Velp', arrives=datetime.datetime(2026, 8, 10, 18, 34, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 34, tzinfo=TzInfo(7200))), Stop(station_uic=8400519, name='Rheden', arrives=datetime.datetime(2026, 8, 10, 18, 38, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 38, tzinfo=TzInfo(7200))), Stop(station_uic=8400176, name='Dieren', arrives=datetime.datetime(2026, 8, 10, 18, 43, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 44, tzinfo=TzInfo(7200))), Stop(station_uic=8400136, name='Brummen', arrives=datetime.datetime(2026, 8, 10, 18, 48, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 48, tzinfo=TzInfo(7200))), Stop(station_uic=8400744, name='Zutphen', arrives=datetime.datetime(2026, 8, 10, 18, 54, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2223: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 6565: _TrainService0(ritnummer=6565, stops=[Stop(station_uic=8400319, name="'s-Hertogenbosch", arrives=None, departs=datetime.datetime(2026, 8, 10, 18, 28, tzinfo=TzInfo(7200))), Stop(station_uic=8400667, name='Vught', arrives=datetime.datetime(2026, 8, 10, 18, 33, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 33, tzinfo=TzInfo(7200))), Stop(station_uic=8400129, name='Boxtel', arrives=datetime.datetime(2026, 8, 10, 18, 39, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 39, tzinfo=TzInfo(7200))), Stop(station_uic=8400112, name='Best', arrives=datetime.datetime(2026, 8, 10, 18, 45, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 45, tzinfo=TzInfo(7200))), Stop(station_uic=8400196, name='Eindhoven Strijp-S', arrives=datetime.datetime(2026, 8, 10, 18, 51, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 51, tzinfo=TzInfo(7200))), Stop(station_uic=8400206, name='Eindhoven Centraal', arrives=datetime.datetime(2026, 8, 10, 18, 55, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 7, tzinfo=TzInfo(7200))), Stop(station_uic=8400242, name='Helmond Brandevoort', arrives=datetime.datetime(2026, 8, 10, 19, 13, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 13, tzinfo=TzInfo(7200))), Stop(station_uic=8400300, name="Helmond 't Hout", arrives=datetime.datetime(2026, 8, 10, 19, 16, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 16, tzinfo=TzInfo(7200))), Stop(station_uic=8400313, name='Helmond', arrives=datetime.datetime(2026, 8, 10, 19, 20, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 20, tzinfo=TzInfo(7200))), Stop(station_uic=8400299, name='Helmond Brouwhuis', arrives=datetime.datetime(2026, 8, 10, 19, 23, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 23, tzinfo=TzInfo(7200))), Stop(station_uic=8400172, name='Deurne', arrives=datetime.datetime(2026, 8, 10, 19, 28, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2224: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 6563: _TrainService0(ritnummer=6563, stops=[Stop(station_uic=8400319, name="'s-Hertogenbosch", arrives=None, departs=datetime.datetime(2026, 8, 10, 17, 58, tzinfo=TzInfo(7200))), Stop(station_uic=8400667, name='Vught', arrives=datetime.datetime(2026, 8, 10, 18, 3, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 3, tzinfo=TzInfo(7200))), Stop(station_uic=8400129, name='Boxtel', arrives=datetime.datetime(2026, 8, 10, 18, 9, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 9, tzinfo=TzInfo(7200))), Stop(station_uic=8400112, name='Best', arrives=datetime.datetime(2026, 8, 10, 18, 15, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 15, tzinfo=TzInfo(7200))), Stop(station_uic=8400196, name='Eindhoven Strijp-S', arrives=datetime.datetime(2026, 8, 10, 18, 21, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 21, tzinfo=TzInfo(7200))), Stop(station_uic=8400206, name='Eindhoven Centraal', arrives=datetime.datetime(2026, 8, 10, 18, 25, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 37, tzinfo=TzInfo(7200))), Stop(station_uic=8400242, name='Helmond Brandevoort', arrives=datetime.datetime(2026, 8, 10, 18, 43, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 43, tzinfo=TzInfo(7200))), Stop(station_uic=8400300, name="Helmond 't Hout", arrives=datetime.datetime(2026, 8, 10, 18, 46, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 46, tzinfo=TzInfo(7200))), Stop(station_uic=8400313, name='Helmond', arrives=datetime.datetime(2026, 8, 10, 18, 50, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 50, tzinfo=TzInfo(7200))), Stop(station_uic=8400299, name='Helmond Brouwhuis', arrives=datetime.datetime(2026, 8, 10, 18, 53, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 53, tzinfo=TzInfo(7200))), Stop(station_uic=8400172, name='Deurne', arrives=datetime.datetime(2026, 8, 10, 18, 58, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2228: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),
 6463: _TrainService0(ritnummer=6463, stops=[Stop(station_uic=8400594, name='Tilburg Universiteit', arrives=None, departs=datetime.datetime(2026, 8, 10, 18, 4, tzinfo=TzInfo(7200))), Stop(station_uic=8400597, name='Tilburg', arrives=datetime.datetime(2026, 8, 10, 18, 8, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 9, tzinfo=TzInfo(7200))), Stop(station_uic=8400482, name='Oisterwijk', arrives=datetime.datetime(2026, 8, 10, 18, 15, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 15, tzinfo=TzInfo(7200))), Stop(station_uic=8400129, name='Boxtel', arrives=datetime.datetime(2026, 8, 10, 18, 22, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 23, tzinfo=TzInfo(7200))), Stop(station_uic=8400112, name='Best', arrives=datetime.datetime(2026, 8, 10, 18, 29, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 29, tzinfo=TzInfo(7200))), Stop(station_uic=8400196, name='Eindhoven Strijp-S', arrives=datetime.datetime(2026, 8, 10, 18, 35, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 35, tzinfo=TzInfo(7200))), Stop(station_uic=8400206, name='Eindhoven Centraal', arrives=datetime.datetime(2026, 8, 10, 18, 39, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 47, tzinfo=TzInfo(7200))), Stop(station_uic=8400245, name='Geldrop', arrives=datetime.datetime(2026, 8, 10, 18, 52, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 52, tzinfo=TzInfo(7200))), Stop(station_uic=8400308, name='Heeze', arrives=datetime.datetime(2026, 8, 10, 18, 56, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 18, 56, tzinfo=TzInfo(7200))), Stop(station_uic=8400432, name='Maarheeze', arrives=datetime.datetime(2026, 8, 10, 19, 3, tzinfo=TzInfo(7200)), departs=datetime.datetime(2026, 8, 10, 19, 3, tzinfo=TzInfo(7200))), Stop(station_uic=8400684, name='Weert', arrives=datetime.datetime(2026, 8, 10, 19, 10, tzinfo=TzInfo(7200)), departs=None)], categoryCode='SPR', categoryName='Sprinter', trainType='Flirt', trainPart_facilities={2231: ['TOILET', 'STROOM', 'FIETS', 'TOEGANKELIJK', 'WIFI']}),

#### Create enums

In [13]:
_category_codes = Counter(x.categoryCode for x in _trains_timetables.values())
CategoryCode = StrEnum('CategoryCode', ((x.upper(), x) for x in _category_codes))
print(_category_codes)

_category_names = Counter(x.categoryName for x in _trains_timetables.values())
CategoryName = StrEnum('CategoryName', ((x.upper(), x) for x in _category_names))
print(_category_names)

_train_types = Counter(x.trainType for x in _trains_timetables.values() if x.trainType)
TrainType = StrEnum('TrainType', ((x.upper(), x) for x in _train_types))
print(_train_types)

_facilities = Counter(
    z
    for x in _trains_timetables.values()
    if x.trainPart_facilities
    for y in x.trainPart_facilities.values()
    for z in y
)
Facility = StrEnum('Facility', ((x.upper(), x) for x in _facilities))
print(_facilities)

Counter({'IC': 144, 'SPR': 138, 'ICD': 10, 'ECD': 4})
Counter({'Intercity': 144, 'Sprinter': 138, 'Intercity direct': 10, 'Eurocity Direct': 4})
Counter({'VIRM': 96, 'SNG': 58, 'SLT': 54, 'Flirt': 25, 'DDZ': 22, 'ICNG': 20, 'ICM': 16})
Counter({'TOILET': 373, 'FIETS': 373, 'WIFI': 299, 'STROOM': 269, 'TOEGANKELIJK': 212, 'STILTE': 188})

#### Apply enums

In [14]:
class TrainService(BaseModel):
    ritnummer: int
    stops: list[Stop]
    categoryCode: CategoryCode
    categoryName: CategoryName
    trainType: TrainType | None
class StockFacility(BaseModel):
    trainType: TrainType
    facilities: list[Facility]

train_timetables = {
    k : TrainService(
        ritnummer= v.ritnummer,
        stops= v.stops,
        categoryCode= CategoryCode(v.categoryCode),
        categoryName= CategoryName(v.categoryName),
        trainType= TrainType(v.trainType) if v.trainType else None,
    )
    for k, v in _trains_timetables.items()
}

_facilities_by_trainType: defaultdict[TrainType, Counter[Facility]] = defaultdict(lambda: Counter[Facility]())
for v in _trains_timetables.values():
    if not(v.trainType) and not(v.trainPart_facilities):
        continue
    _facilities_by_trainType[v.trainType].update(
        Facility(x)
        for facilities in v.trainPart_facilities.values()
        for x in facilities
    )
print(json.dumps(_facilities_by_trainType, indent=4))

facilities_by_trainType: dict[TrainType, list[Facility]] = {
    k : list[Facility](v.keys())
    for k, v in _facilities_by_trainType.items()
}

{
    "Flirt": {
        "TOILET": 28,
        "STROOM": 28,
        "FIETS": 28,
        "TOEGANKELIJK": 28,
        "WIFI": 28
    },
    "SNG": {
        "FIETS": 83,
        "WIFI": 83,
        "STROOM": 83,
        "TOEGANKELIJK": 83,
        "TOILET": 83
    },
    "SLT": {
        "FIETS": 74,
        "TOILET": 74,
        "TOEGANKELIJK": 74
    },
    "ICNG": {
        "WIFI": 27,
        "TOILET": 27,
        "STILTE": 27,
        "STROOM": 27,
        "FIETS": 27,
        "TOEGANKELIJK": 27
    },
    "ICM": {
        "WIFI": 27,
        "TOILET": 27,
        "STILTE": 27,
        "STROOM": 27,
        "FIETS": 27
    },
    "DDZ": {
        "WIFI": 25,
        "TOILET": 25,
        "STILTE": 25,
        "STROOM": 25,
        "FIETS": 25
    },
    "VIRM": {
        "WIFI": 109,
        "TOILET": 109,
        "STILTE": 109,
        "FIETS": 109,
        "STROOM": 79
    }
}

## Get train stations

In [15]:
# STATIONS '/v3' https://apiportal.ns.nl/api-details#api=nsapp-stations-api&operation=getStationsV3
# payload.id.uicCode
# payload.id.code # eg UT for Utrecht Centraal
# payload.stationType (enum)
# payload.names.long/medium/short/festive/synonyms[]
# payload.location.lat/lng (number)

In [16]:
stations_pkl = raw_out_dir / 'stations.pkl'
if not stations_pkl.exists():
    response = requests.get(NSAPI_URLS['STATIONS'] + '/v3', headers=NS_GET_HEADER,
        params=nsapi.nsapp_stations.V3GetParameters(
            countryCodes=['NL'],
            limit=None # irrelevant when not providing str `q`
        )
    )
    obj = nsapi.nsapp_stations.StationsV3Response(**response.json())
    with open(stations_pkl, 'wb') as file:
        pickle.dump(obj, file, protocol=-1)
else:
    with open(stations_pkl, 'rb') as file:
        obj = pickle.load(file)

In [17]:
StationInfo = NamedTuple('StationInfo', (
    ('name', str),
    ('lat', float),
    ('lng', float),
))

stations_by_uicCode: dict[int, StationInfo] = {
    int(x.id.uicCode) : StationInfo(
        name=x.names.long,
        lat=x.location.lat,
        lng=x.location.lng,
    )
    for x in obj.payload
}

_uics = sorted(stations_by_uicCode.keys())
_names_len = sorted(
    (x.name for x in stations_by_uicCode.values()),
    key=len
)
_names_words = sorted(
    (x.name for x in stations_by_uicCode.values()),
    key=lambda s: len(s.split())
)
print(_uics[:1] + ['...'] + _uics[-1:])
print('========')
print(_names_len[:3] + ['...'] + _names_len[-3:])
print('========')
print(_names_words[:3] + ['...'] + _names_words[-3:])

[8400045, '...', 8400752]
========
['Oss', 'Olst', 'Elst', '...', 'Bovenkarspel-Grootebroek', 'Lansingerland-Zoetermeer', 'Leeuwarden Camminghaburen']
========
["'s-Hertogenbosch", 'Alkmaar', 'Almelo', '...', 'Zandvoort aan Zee', 'Koog aan de Zaan', 'Den Haag Laan v NOI']

## Export for SQL

In [18]:
reveal_type(trains_type_by_id)
reveal_type(train_timetables)
reveal_type(facilities_by_trainType)
reveal_type(stations_by_uicCode)

Runtime type is 'dict'
Runtime type is 'dict'
Runtime type is 'dict'
Runtime type is 'dict'

{8400301: StationInfo(name='Heerenveen IJsstadion', lat=52.9352760314941, lng=5.94388866424561),
 8400534: StationInfo(name='Rotterdam Stadion', lat=51.8938903808594, lng=4.51972198486328),
 8400058: StationInfo(name='Amsterdam Centraal', lat=52.3788871765137, lng=4.90027761459351),
 8400282: StationInfo(name='Den Haag Centraal', lat=52.0802764892578, lng=4.32499980926514),
 8400206: StationInfo(name='Eindhoven Centraal', lat=51.4433326721191, lng=5.48138904571533),
 8400530: StationInfo(name='Rotterdam Centraal', lat=51.9249992370605, lng=4.46888875961304),
 8400561: StationInfo(name='Schiphol Airport', lat=52.3094444274902, lng=4.76194429397583),
 8400621: StationInfo(name='Utrecht Centraal', lat=52.0888900756836, lng=5.11027765274048),
 8400319: StationInfo(name="'s-Hertogenbosch", lat=51.69048, lng=5.29362),
 8400050: StationInfo(name='Alkmaar', lat=52.6377792358398, lng=4.73972225189209),
 8400051: StationInfo(name='Almelo', lat=52.3580551147461, lng=6.65388870239258),
 8400080: StationInfo(name='Almere Centrum', lat=52.37503, lng=5.21764),
 8400053: StationInfo(name='Alphen a/d Rijn', lat=52.1244430541992, lng=4.65777778625488),
 8400055: StationInfo(name='Amersfoort Centraal', lat=52.1538887023926, lng=5.37055540084839),
 8400059: StationInfo(name='Amsterdam Sloterdijk', lat=52.3888893127441, lng=4.83777761459351),
 8400066: StationInfo(name='Apeldoorn', lat=52.2091674804687, lng=5.97027778625488),
 8400071: StationInfo(name='Arnhem Centraal', lat=51.9850006103516, lng=5.89916658401489),
 8400073: StationInfo(name='Assen', lat=52.9916648864746, lng=6.57083320617676),
 8400131: StationInfo(name='Breda', lat=51.5955543518066, lng=4.78000020980835),
 8400170: StationInfo(name='Delft', lat=52.0066680908203, lng=4.35638904571533),
 8400280: StationInfo(name='Den Haag HS', lat=52.0697212219238, lng=4.32250022888184),
 8400173: StationInfo(name='Deventer', lat=52.2574996948242, lng=6.16055536270142),
 8400180: StationInfo(name='Dordrecht', lat=51.8072204589844, lng=4.66833353042603),
 8400200: StationInfo(name='Ede-Wageningen', lat=52.0277786254883, lng=5.67305564880371),
 8400212: StationInfo(name='Enschede', lat=52.2224998474121, lng=6.8899998664856),
 8400258: StationInfo(name='Gouda', lat=52.0175018310547, lng=4.70444440841675),
 8400263: StationInfo(name='Groningen', lat=53.2105560302734, lng=6.56472206115723),
 8400285: StationInfo(name='Haarlem', lat=52.3877792358398, lng=4.63833332061768),
 8400307: StationInfo(name='Heerlen', lat=50.8908348083496, lng=5.97499990463257),
 8400313: StationInfo(name='Helmond', lat=51.4755554199219, lng=5.66194438934326),
 8400316: StationInfo(name='Hengelo', lat=52.2616653442383, lng=6.79388904571533),
 8400322: StationInfo(name='Hilversum', lat=52.2258338928223, lng=5.18194437026978),
 8400337: StationInfo(name='Hoorn', lat=52.6447219848633, lng=5.05555534362793),
 8400387: StationInfo(name='Leeuwarden', lat=53.1958351135254, lng=5.79222202301025),
 8400390: StationInfo(name='Leiden Centraal', lat=52.1661109924316, lng=4.48166656494141),
 8400394: StationInfo(name='Lelystad Centrum', lat=52.5077781677246, lng=5.47277784347534),
 8400424: StationInfo(name='Maastricht', lat=50.8502769470215, lng=5.70555543899536),
 8400470: StationInfo(name='Nijmegen', lat=51.8436126708984, lng=5.85222244262695),
 8400495: StationInfo(name='Oss', lat=51.7655563354492, lng=5.53222227096558),
 8400523: StationInfo(name='Roermond', lat=51.1930541992188, lng=5.9941668510437),
 8400526: StationInfo(name='Roosendaal', lat=51.5402793884277, lng=4.45833349227905),
 8400564: StationInfo(name='Sittard', lat=51.0016670227051, lng=5.85861110687256),
 8400597: StationInfo(name='Tilburg', lat=51.5605545043945, lng=5.08361101150513),
 8400644: StationInfo(name='Venlo', lat=51.3636093139648, lng=6.17277765274048),
 8400652: StationInfo(name='Vlissingen', lat=51.4458351135254, lng=3.59527778625488),
 8400731: StationInfo(name='Zaandam', lat=52.4388885498047, lng=4.81361103057861),
 8400744: StationInfo(name='Zutphen', lat=52.1452789306641, lng=6.19416666030884),
 8400747: StationInfo(name='Zwolle', lat=52.5047225952148, lng=6.09194421768188),
 8400057: StationInfo(name='Amsterdam Amstel', lat=52.3466682434082, lng=4.91777801513672),
 8400061: StationInfo(name='Amsterdam Zuid', lat=52.338889, lng=4.872356),
 8400151: StationInfo(name='Castricum', lat=52.5458335876465, lng=4.65861129760742),
 8400311: StationInfo(name='Den Helder', lat=52.9552764892578, lng=4.76111125946045),
 8400176: StationInfo(name='Dieren', lat=52.0449981689453, lng=6.10305547714233),
 8400218: StationInfo(name='Etten-Leur', lat=51.5750007629395, lng=4.63583326339722),
 8400302: StationInfo(name='Heemstede-Aerdenhout', lat=52.3591651916504, lng=4.60666656494141),
 8400305: StationInfo(name='Heerenveen', lat=52.9613876342773, lng=5.91416645050049),
 8400486: StationInfo(name='Olst', lat=52.3347206115723, lng=6.11305570602417),
 8400507: StationInfo(name='Rotterdam Alexander', lat=51.9519462585449, lng=4.55361127853394),
 8400578: StationInfo(name='Steenwijk', lat=52.7915109924316, lng=6.11455576324463),
 8400684: StationInfo(name='Weert', lat=51.2486114501953, lng=5.70361089706421),
 8400711: StationInfo(name='Wijhe', lat=52.3902778625488, lng=6.1405553817749),
 8400139: StationInfo(name='Buitenpost', lat=53.2564547, lng=6.1446496),
 8400153: StationInfo(name='Coevorden', lat=52.6636123657227, lng=6.73555564880371),
 8400428: StationInfo(name='Mariënberg', lat=52.5094451904297, lng=6.57527780532837),
 8400487: StationInfo(name='Ommen', lat=52.5094451904297, lng=6.41583347320557),
 8400632: StationInfo(name='Valkenburg', lat=50.8697204589844, lng=5.83222198486328),
 8400167: StationInfo(name='Dalfsen', lat=52.4983329772949, lng=6.25861120223999),
 8400208: StationInfo(name='Emmen', lat=52.7900009155273, lng=6.89944458007812),
 8400407: StationInfo(name='Emmen Zuid', lat=52.7488663746914, lng=6.87478065490722),
 8400293: StationInfo(name='Hardenberg', lat=52.5727767944336, lng=6.62861108779907),
 8400434: StationInfo(name='Meerssen', lat=50.882879392551, lng=5.75099945068359),
 8400454: StationInfo(name='Nieuw Amsterdam', lat=52.7186126708984, lng=6.84861087799072),
 8400074: StationInfo(name='Amsterdam Bijlmer ArenA', lat=52.3122215270996, lng=4.94694423675537),
 8400086: StationInfo(name='Baarn', lat=52.2083320617676, lng=5.28083324432373),
 8400457: StationInfo(name='Bad Nieuweschans', lat=53.1844, lng=7.19937),
 8400128: StationInfo(name='Boxmeer', lat=51.6445217676531, lng=5.93903303146362),
 8400129: StationInfo(name='Boxtel', lat=51.58433, lng=5.31912),
 8400133: StationInfo(name='Breukelen', lat=52.17149, lng=4.9906),
 8400179: StationInfo(name='Den Dolder', lat=52.1402778625488, lng=5.24277782440186),
 8400380: StationInfo(name='Den Haag Laan v NOI', lat=52.0786094665527, lng=4.34277772903442),
 8400177: StationInfo(name='Doetinchem', lat=51.9585962, lng=6.2962148),
 8400182: StationInfo(name='Driebergen-Zeist', lat=52.0652770996094, lng=5.25861120223999),
 8400194: StationInfo(name='Duivendrecht', lat=52.3233337402344, lng=4.93638896942139),
 8400207: StationInfo(name='Elst', lat=51.9169425964355, lng=5.85500001907349),
 8400244: StationInfo(name='Geldermalsen', lat=51.88301, lng=5.27127),
 8400245: StationInfo(name='Geldrop', lat=51.4197235107422, lng=5.55055570602417),
 8400256: StationInfo(name='Gorinchem', lat=51.8338890075684, lng=4.96833324432373),
 8400294: StationInfo(name='Harderwijk', lat=52.3375015258789, lng=5.61972236633301),
 8400306: StationInfo(name='Heerhugowaard', lat=52.6697235107422, lng=4.82277774810791),
 8400331: StationInfo(name='Hoogezand-Sappemeer', lat=53.1598181316756, lng=6.77075386047363),
 8400340: StationInfo(name='Houten', lat=52.03402, lng=5.16821),
 8400355: StationInfo(name='Kerkrade Centrum', lat=50.8616676330566, lng=6.05749988555908),
 8400382: StationInfo(name='Lage Zwaluwe', lat=51.6911125183105, lng=4.66305541992188),
 8400548: StationInfo(name='Landgraaf', lat=50.8963890075684, lng=6.01916646957398),
 8400417: StationInfo(name='Maarn', lat=52.0641670227051, lng=5.36999988555908),
 8400426: StationInfo(name='Maastricht Randwyck', lat=50.8386116027832, lng=5.71722221374512),
 8400435: StationInfo(name='Meppel', lat=52.6908340454102, lng=6.19750022888184),
 8400452: StationInfo(name='Naarden-Bussum', lat=52.2802772521973, lng=5.15694427490234),
 8400508: StationInfo(name='Purmerend', lat=52.5030555725098, lng=4.95361089706421),
 8400517: StationInfo(name='Rhenen', lat=51.958610534668, lng=5.57833337783814),
 8400566: StationInfo(name='Sneek', lat=53.0328688, lng=5.6523969),
 8400567: StationInfo(name='Soest', lat=52.1733322143555, lng=5.30999994277954),
 8400596: StationInfo(name='Tiel', lat=51.8894462585449, lng=5.42222213745117),
 8400615: StationInfo(name='Uitgeest', lat=52.5216674804687, lng=4.70166683197022),
 8400620: StationInfo(name='Utrecht Overvecht', lat=52.1100006103516, lng=5.12472200393677),
 8400606: StationInfo(name='Utrecht Vaartsche Rijn', lat=52.078889, lng=5.121667),
 8400636: StationInfo(name='Veendam', lat=53.10324, lng=6.88475),
 8400627: StationInfo(name='Veenendaal Centrum', lat=52.0200004577637, lng=5.54861116409302),
 8400646: StationInfo(name='Venray', lat=51.526568099007, lng=6.01417779922485),
 8400685: StationInfo(name='Weesp', lat=52.3127784729004, lng=5.04305553436279),
 8400691: StationInfo(name='Wierden', lat=52.3613891601562, lng=6.59166669845581),
 8400696: StationInfo(name='Winschoten', lat=53.1392377, lng=7.035101),
 8400698: StationInfo(name='Winterswijk', lat=51.9677307, lng=6.7155181),
 8400702: StationInfo(name='Woerden', lat=52.0849990844727, lng=4.89361095428467),
 8400364: StationInfo(name='Zaandijk Zaanse Schans', lat=52.469165802002, lng=4.80499982833862),
 8400735: StationInfo(name='Zevenaar', lat=51.9230537414551, lng=6.07194423675537),
 8400741: StationInfo(name='Zoetermeer', lat=52.0475006103516, lng=4.47722244262695),
 8400742: StationInfo(name='Zuidbroek', lat=53.1596122800056, lng=6.8679141998291),
 8400320: StationInfo(name="'s-Hertogenbosch Oost", lat=51.700553894043, lng=5.3183331489563),
 8400388: StationInfo(name="'t Harde", lat=52.4091682, lng=5.893611),
 8400045: StationInfo(name='Aalten', lat=51.9213265245505, lng=6.57862722873687),
 8400047: StationInfo(name='Abcoude', lat=52.2785, lng=4.977),
 8400049: StationInfo(name='Akkrum', lat=53.0463905334473, lng=5.84361124038696),
 8400052: StationInfo(name='Alkmaar Noord', lat=52.6438903808594, lng=4.76416683197022),
 8400520: StationInfo(name='Almelo de Riet', lat=52.3419456481934, lng=6.66666650772095),
 8400081: StationInfo(name='Almere Buiten', lat=52.3941650390625, lng=5.2780556678772),
 8400082: StationInfo(name='Almere Muziekwijk', lat=52.3675003051758, lng=5.19027757644653),
 8400226: StationInfo(name='Almere Oostvaarders', lat=52.4033317565918, lng=5.30055570602417),
 8400104: StationInfo(name='Almere Parkwijk', lat=52.3766670227051, lng=5.24472236633301),
 8400450: StationInfo(name='Almere Poort', lat=52.342778, lng=5.151944),
 8400054: StationInfo(name='Amersfoort Schothorst', lat=52.1748221374512, lng=5.40388870239258),
 8400228: StationInfo(name='Amersfoort Vathorst', lat=52.1927795410156, lng=5.43388891220093),
 8400231: StationInfo(name='Amsterdam Holendrecht', lat=52.29844, lng=4.95972),
 8400079: StationInfo(name='Amsterdam Lelylaan', lat=52.3577766418457, lng=4.83388900756836),
 8400060: StationInfo(name='Amsterdam Muiderpoort', lat=52.3605537414551, lng=4.93111133575439),
 8400056: StationInfo(name='Amsterdam RAI', lat=52.3372230529785, lng=4.89027786254883),
 8400235: StationInfo(name='Amsterdam Science Park', lat=52.35274, lng=4.94855),
 8400065: StationInfo(name='Anna Paulowna', lat=52.8672218322754, lng=4.81111097335815),
 8400233: StationInfo(name='Apeldoorn De Maten', lat=52.2052764892578, lng=6.00055551528931),
 8400229: StationInfo(name='Apeldoorn Osseveld', lat=52.2152786254883, lng=6.00444459915161),
 8400067: StationInfo(name='Appingedam', lat=53.3258135, lng=6.8619577),
 8400068: StationInfo(name='Arkel', lat=51.8719444274902, lng=4.99277782440186),
 8400069: StationInfo(name='Arnemuiden', lat=51.5016670227051, lng=3.66916656494141),
 8400075: StationInfo(name='Arnhem Presikhaaf', lat=51.9880561828613, lng=5.94388866424561),
 8400072: StationInfo(name='Arnhem Velperpoort', lat=51.985279083252, lng=5.91944456100464),
 8400227: StationInfo(name='Arnhem Zuid', lat=51.9550018310547, lng=5.85194444656372),
 8400089: StationInfo(name='Baflo', lat=53.3608969, lng=6.5185581),
 8400090: StationInfo(name='Barendrecht', lat=51.8547210693359, lng=4.5533332824707),
 8400091: StationInfo(name='Barneveld Centrum', lat=52.1399993896484, lng=5.59027767181396),
 8400092: StationInfo(name='Barneveld Noord', lat=52.1613883972168, lng=5.59805536270142),
 8400115: StationInfo(name='Barneveld Zuid', lat=52.128853, lng=5.60246),
 8400094: StationInfo(name='Bedum', lat=53.3068857, lng=6.593054),
 8400096: StationInfo(name='Beek-Elsloo', lat=50.9474983215332, lng=5.78666687011719),
 8400097: StationInfo(name='Beesd', lat=51.8994445800781, lng=5.19444465637207),
 8400100: StationInfo(name='Beilen', lat=52.8547210693359, lng=6.52111101150513),
 8400108: StationInfo(name='Bergen op Zoom', lat=51.4938888549805, lng=4.29611110687256),
 8400112: StationInfo(name='Best', lat=51.5099983215332, lng=5.38916683197022),
 8400113: StationInfo(name='Beverwijk', lat=52.4783325195313, lng=4.65666675567627),
 8400114: StationInfo(name='Bilthoven', lat=52.1300010681152, lng=5.20388889312744),
 8400117: StationInfo(name='Blerick', lat=51.372501373291, lng=6.15500020980835),
 8400118: StationInfo(name='Bloemendaal', lat=52.404167175293, lng=4.62750005722046),
 8400121: StationInfo(name='Bodegraven', lat=52.0813903808594, lng=4.7461109161377),
 8400124: StationInfo(name='Borne', lat=52.2988891601562, lng=6.74805545806885),
 8400125: StationInfo(name='Boskoop', lat=52.0777778625488, lng=4.64694452285767),
 8400126: StationInfo(name='Boskoop Snijdelwijk', lat=52.067658, lng=4.646186),
 8400236: StationInfo(name='Boven-Hardinxveld', lat=51.832222, lng=4.878056),
 8400230: StationInfo(name='Bovenkarspel Flora', lat=52.6961097717285, lng=5.25277757644653),
 8400127: StationInfo(name='Bovenkarspel-Grootebroek', lat=52.6949996948242, lng=5.23777770996094),
 8400132: StationInfo(name='Breda-Prinsenbeek', lat=51.606388092041, lng=4.72083330154419),
 8400136: StationInfo(name='Brummen', lat=52.0911102294922, lng=6.14694452285767),
 8400140: StationInfo(name='Bunde', lat=50.8969459533691, lng=5.73666667938232),
 8400141: StationInfo(name='Bunnik', lat=52.0630569458008, lng=5.19444465637207),
 8400145: StationInfo(name='Bussum Zuid', lat=52.2658348083496, lng=5.16305541992188),
 8400147: StationInfo(name='Capelle Schollevaar', lat=51.9541664123535, lng=4.58416652679443),
 8400152: StationInfo(name='Chevremont', lat=50.8761100769043, lng=6.05972242355347),
 8400155: StationInfo(name='Cuijk', lat=51.7266825879048, lng=5.87429523468017),
 8400154: StationInfo(name='Culemborg', lat=51.9466667175293, lng=5.22694444656372),
 8400164: StationInfo(name='Daarlerveen', lat=52.4407702, lng=6.5759947),
 8400161: StationInfo(name='Dalen', lat=52.6941680908203, lng=6.75805568695068),
 8400188: StationInfo(name='De Vink', lat=52.1472206115723, lng=4.4563889503479),
 8400745: StationInfo(name='De Westereen', lat=53.24817, lng=6.03463),
 8400168: StationInfo(name='Deinum', lat=53.1888115, lng=5.7281572),
 8400169: StationInfo(name='Delden', lat=52.2599983215332, lng=6.7161111831665),
 8400166: StationInfo(name='Delft Campus', lat=51.9908332824707, lng=4.36472225189209),
 8400171: StationInfo(name='Delfzijl', lat=53.3336625, lng=6.9240797),
 8400175: StationInfo(name='Delfzijl West', lat=53.3320834, lng=6.9069092),
 8400278: StationInfo(name='Den Haag Mariahoeve', lat=52.0905570983887, lng=4.36944437026978),
 8400279: StationInfo(name='Den Haag Moerwijk', lat=52.0538902282715, lng=4.3086109161377),
 8400379: StationInfo(name='Den Haag Ypenburg', lat=52.0552787780762, lng=4.39222240447998),
 8400303: StationInfo(name='Den Helder Zuid', lat=52.9324989318848, lng=4.76416683197022),
 8400172: StationInfo(name='Deurne', lat=51.4558334350586, lng=5.78888893127441),
 8400185: StationInfo(name='Deventer Colmschate', lat=52.2502784729004, lng=6.21444463729858),
 8400174: StationInfo(name='Didam', lat=51.933502, lng=6.1324106),
 8400165: StationInfo(name='Diemen', lat=52.34515, lng=4.967566),
 8400163: StationInfo(name='Diemen Zuid', lat=52.3302764892578, lng=4.95583343505859),
 8400184: StationInfo(name='Doetinchem De Huet', lat=51.9591413, lng=6.2598521),
 8400186: StationInfo(name='Dordrecht Stadspolders', lat=51.801944732666, lng=4.71666669845581),
 8400181: StationInfo(name='Dordrecht Zuid', lat=51.7900009155273, lng=4.67138910293579),
 8400183: StationInfo(name='Driehuis', lat=52.4425010681152, lng=4.63805532455444),
 8400192: StationInfo(name='Dronryp', lat=53.1778086, lng=5.6347411),
 8400198: StationInfo(name='Dronten', lat=52.5344, lng=5.72089),
 8400193: StationInfo(name='Duiven', lat=51.9433326721191, lng=6.01472234725952),
 8400195: StationInfo(name='Echt', lat=51.1005554199219, lng=5.87888908386231),
 8400201: StationInfo(name='Ede Centrum', lat=52.0436096191406, lng=5.66833353042603),
 8400202: StationInfo(name='Eemshaven', lat=53.458419, lng=6.832),
 8400219: StationInfo(name='Eijsden', lat=50.7719459533691, lng=5.71000003814697),
 8400196: StationInfo(name='Eindhoven Strijp-S', lat=51.4511108398438, lng=5.45583343505859),
 8400210: StationInfo(name='Enkhuizen', lat=52.6991653442383, lng=5.28638887405396),
 8400217: StationInfo(name='Enschede De Eschmarke', lat=52.2213897705078, lng=6.95111131668091),
 8400221: StationInfo(name='Enschede Kennispark', lat=52.2374992370605, lng=6.83888912200928),
 8400216: StationInfo(name='Ermelo', lat=52.3016662597656, lng=5.61472225189209),
 8400338: StationInfo(name='Eygelshoven', lat=50.8905563354492, lng=6.04500007629395),
 8400234: StationInfo(name='Eygelshoven Markt', lat=50.8960498196442, lng=6.0602474212646396),
 8400638: StationInfo(name='Feanwâlden', lat=53.2351834, lng=5.9886615),
 8400232: StationInfo(name='Franeker', lat=53.1824488, lng=5.5483094),
 8400241: StationInfo(name='Gaanderen', lat=51.93074, lng=6.3486),
 8400246: StationInfo(name='Geleen Oost', lat=50.9669456481934, lng=5.84305572509766),
 8400248: StationInfo(name='Geleen-Lutterade', lat=50.9755554199219, lng=5.82472229003906),
 8400251: StationInfo(name='Gilze-Rijen', lat=51.583610534668, lng=4.92611122131348),
 8400262: StationInfo(name='Glanerbrug', lat=52.2186126708984, lng=6.97444438934326),
 8400253: StationInfo(name='Goes', lat=51.4980545043945, lng=3.89055562019348),
 8400254: StationInfo(name='Goor', lat=52.2302780151367, lng=6.58444452285767),
 8400257: StationInfo(name='Gouda Goverwelle', lat=52.0149993896484, lng=4.7408332824707),
 8400259: StationInfo(name='Gramsbergen', lat=52.6091651916504, lng=6.67583322525024),
 8400267: StationInfo(name='Grijpskerk', lat=53.2557403255735, lng=6.30977869033813),
 8400238: StationInfo(name='Groningen Europapark', lat=53.20480027, lng=6.5854178),
 8400264: StationInfo(name='Groningen Noord', lat=53.2301469, lng=6.5563172),
 8400266: StationInfo(name='Grou-Jirnsum', lat=53.0888900756836, lng=5.82250022888184),
 8400270: StationInfo(name='Haarlem Spaarnwoude', lat=52.3827781677246, lng=4.67305564880371),
 8400400: StationInfo(name='Halfweg-Zwanenburg', lat=52.385935, lng=4.747165),
 8400438: StationInfo(name='Hardinxveld Blauwe Zoom', lat=51.82944, lng=4.815663),
 8400295: StationInfo(name='Hardinxveld-Giessendam', lat=51.8305549621582, lng=4.83583354949951),
 8400297: StationInfo(name='Haren', lat=53.1761093139648, lng=6.61722230911255),
 8400296: StationInfo(name='Harlingen', lat=53.1704205, lng=5.4251932),
 8400298: StationInfo(name='Harlingen Haven', lat=53.174917, lng=5.4112885),
 8400317: StationInfo(name='Heemskerk', lat=52.4952774047852, lng=4.68694448471069),
 8400404: StationInfo(name='Heerlen Woonboulevard', lat=50.896667, lng=5.952222),

In [19]:
geolocator = Nominatim(user_agent="ns_train_stations_scraper")
geolocator_rate_limited = RateLimiter(geolocator.reverse, min_delay_seconds=2)

In [20]:
addresses_pkl = raw_out_dir / 'addresses.pkl'
if not addresses_pkl.exists():
    sql_stations = pd.DataFrame({
        'uic': uic,
        'name': v.name,
        'lat': v.lat,
        'lng': v.lng,
        'address': geolocator_rate_limited(f"{v.lat}, {v.lng}").address,
    }   for uic, v in stations_by_uicCode.items())
    with open(addresses_pkl, 'xb') as file:
        pickle.dump(sql_stations, file, protocol=-1)
else:
    with open(addresses_pkl, 'r+b') as file:
        sql_stations = pickle.load(file)

In [21]:
sql_trainsetamenities = pd.DataFrame([
    {
        'trainset': trainset,
        'amenity': amenity,
    }
    for trainset, facilities in facilities_by_trainType.items()
    for amenity in facilities
])
sql_trainsetamenities

   trainset       amenity
0     Flirt        TOILET
1     Flirt        STROOM
2     Flirt         FIETS
3     Flirt  TOEGANKELIJK
4     Flirt          WIFI
5       SNG         FIETS
6       SNG          WIFI
7       SNG        STROOM
8       SNG  TOEGANKELIJK
9       SNG        TOILET
10      SLT         FIETS
11      SLT        TOILET
12      SLT  TOEGANKELIJK
13     ICNG          WIFI
14     ICNG        TOILET
15     ICNG        STILTE
16     ICNG        STROOM
17     ICNG         FIETS
18     ICNG  TOEGANKELIJK
19      ICM          WIFI
20      ICM        TOILET
21      ICM        STILTE
22      ICM        STROOM
23      ICM         FIETS
24      DDZ          WIFI
25      DDZ        TOILET
26      DDZ        STILTE
27      DDZ        STROOM
28      DDZ         FIETS
29     VIRM          WIFI
30     VIRM        TOILET
31     VIRM        STILTE
32     VIRM         FIETS
33     VIRM        STROOM

In [22]:
sql_passservice = pd.DataFrame([
    {
        'num': k,
        'name': f"{v.categoryName} {v.ritnummer} to {v.stops[-1].name}",
        'trainset': v.trainType if v.trainType
                    else TrainType.SLT if v.ritnummer == 9571
                    else TrainType.ICNG if v.categoryCode == CategoryCode.ECD
                    else None,
    }
    for k, v in train_timetables.items()
])

In [23]:
sql_stop = pd.DataFrame([
    {
        'passservice_num': passservice_id,
        'arrival': stop.arrives,
        'departure': stop.departs,
        'stations_uic': stop.station_uic,
    }
    for passservice_id, passservice in train_timetables.items()
    for stop in passservice.stops
])

## Final cleanup/asserts

In [24]:
# delete rows missing both arrival/departure
sql_stop = sql_stop[~sql_stop[['arrival', 'departure']].isna().all(axis='columns')]

In [25]:
sql_stop.loc[sql_stop['arrival'] == sql_stop['departure'], 'departure'] += timedelta(seconds=30)
sql_stop.loc[sql_stop['arrival'] == sql_stop['departure']]

Empty DataFrame
Columns: [passservice_num, arrival, departure, stations_uic]
Index: []

In [26]:
# double-check, in sql_stop, that only first and last stops are missing arrival/departure
stops_sorted_groups = sql_stop.sort_values('arrival', na_position='first').groupby('passservice_num')
heads_departures = stops_sorted_groups.apply(lambda group: group['departure'].iloc[:-1])
tails_arrivals = stops_sorted_groups.apply(lambda group: group['arrival'].iloc[1:])
assert(heads_departures.notna().all().all())
assert(tails_arrivals.notna().all().all())

In [27]:
# fill first arrival, last departure with midnight the day before/after
first_arrival_update = sql_stop[['passservice_num', 'arrival']]
first_arrival_update = first_arrival_update.sort_values('arrival', na_position='first')
first_arrival_update['arrival'] = first_arrival_update['arrival'].dt.floor('D')
first_arrival_update['arrival'] = first_arrival_update.groupby('passservice_num')['arrival'].bfill(limit=1)
first_arrival_update = first_arrival_update.groupby('passservice_num').nth(0)
sql_stop['arrival'] = first_arrival_update['arrival'].reindex_like(sql_stop).where(pd.notna, sql_stop['arrival'])

last_departure_update = sql_stop[['passservice_num', 'arrival', 'departure']]
last_departure_update = last_departure_update.sort_values('arrival', na_position='first')
last_departure_update['departure'] = last_departure_update['departure'].dt.ceil('D')
last_departure_update['departure'] = last_departure_update.groupby('passservice_num')['departure'].ffill(limit=1)
last_departure_update = last_departure_update.groupby('passservice_num').nth(-1)
sql_stop['departure'] = last_departure_update['departure'].reindex_like(sql_stop).where(pd.notna, sql_stop['departure'])

In [28]:
# double-check table keys
assert (set(sql_passservice['trainset']) == set(sql_trainsetamenities['trainset']))
assert (set(sql_stop['stations_uic']) < set(sql_stations['uic']))
assert (set(sql_stop['passservice_num']) == set(sql_passservice['num']))

AssertionError:

In [ ]:
# also check which columns of any tables are nullable
assert (sql_stop.notna().all().all())
assert (sql_stations.notna().all().all())
assert (sql_passservice.notna().all().all())
assert (sql_trainsetamenities.notna().all().all())
# print('sql_stop', sql_stop.notna().all(axis='index'))
# print('sql_stations', sql_stations.notna().all(axis='index'))
# print('sql_passservice', sql_passservice.notna().all(axis='index'))
# print('sql_trainsetamenities', sql_trainsetamenities.notna().all(axis='index'))

## Export

In [ ]:
# export with .to_csv()
sql_stations.to_csv(out_dir / 'stations.csv')
sql_trainsetamenities.to_csv(out_dir / 'trainsetamenities.csv')
sql_passservice.to_csv(out_dir / 'passservice.csv')
sql_stop.to_csv(out_dir / 'stop.csv')

# UNUSED BELOW

## Get train stock

In [ ]:
# TREIN '/v1/trein' https://apiportal.ns.nl/api-details#api=virtual-train-API&operation=getTrainInformation
# TREINRIT '/v1/trein/{ritnummer}' https://apiportal.ns.nl/api-details#api=virtual-train-API&operation=getTrainInformationForRitnummer
# STATION VAN TREINRIT '/v1/trein/{ritnummer}/{stationscode}' https://apiportal.ns.nl/api-details#api=virtual-train-API&operation=getTrainInformationForRitnummerAndStationCode

# (Below are available from the three APIs above, but not all are applicable without specifying Rit and/or Station.)
# (Één MaterieelDeel bestaat uit meerdere Bakken.)

# TreinInformatie.ritnummer (int)
# TreinInformatie.type (string)
# TreinInformatie.geplandeMaterieeldelen[].materieelType (string)
# TreinInformatie.geplandeMaterieeldelen[].materieelnummer (int)
# TreinInformatie.geplandeMaterieeldelen[].type (string)
# TreinInformatie.geplandeMaterieeldelen[].faciliteiten (string[])

In [ ]:
# trein_pkl = Path('./ns_results/raw/trein_info.pkl')
# if not trein_pkl.exists():
#     response = requests.get(NSAPI_URLS['VIRTUAL_TRAIN'] + '/v1' + '/trein', headers=NS_GET_HEADER,
#         params=nsapi.virtual_train.ApiV1TreinGetParameters(
#             ids=train_id,
#             # dateTime=(datetime.today() + timedelta(days=1)).isoformat().__str__(),
#             all=True,
#         )
#     )
#     print('Response:', response.json())
#     obj = nsapi.virtual_train.TreinInformatie(**response.json())
#     with open(trein_pkl, 'wb') as file:
#         pickle.dump(obj, file, protocol=-1)
# else:
#     with open(trein_pkl, 'rb') as file:
#         obj = pickle.load(file)

In [ ]:
# do we want to do /trein/ritnummer?
# trein_rit_pkl = Path('./ns_results/raw/trein_met_ritnummer_info.pkl')
# if not trein_rit_pkl.exists():
#     response = requests.get(NSAPI_URLS['VIRTUAL_TRAIN'] + '/v1' + f'/trein/{ritnummer}', headers=NS_GET_HEADER,
#         params=nsapi.virtual_train.ApiV1TreinRitnummerGetParameters(
#             # countryCodes=['NL'],
#             # limit=None # irrelevant when not providing str `q`
#         )
#     )
#     obj = nsapi.virtual_train.TreinInformatie(**response.json())
#     with open(trein_rit_pkl, 'wb') as file:
#         pickle.dump(obj, file, protocol=-1)
# else:
#     with open(trein_rit_pkl, 'rb') as file:
#         obj = pickle.load(file)

In [ ]:
# do we want to do /trein/ritnummer/stationscode?
# trein_rit_stations_pkl = Path('./ns_results/raw/trein_met_ritnummer_en_stationscode_info.pkl')
# if not trein_rit_stations_pkl.exists():
#     response = requests.get(NSAPI_URLS['VIRTUAL_TRAIN'] + '/v1' + f'/trein/{ritnummer}/{stationscode}', headers=NS_GET_HEADER,
#         params=nsapi.virtual_train.ApiV1TreinRitnummerStationscodeGetParameters(
#             # countryCodes=['NL'],
#             # limit=None # irrelevant when not providing str `q`
#         )
#     )
#     obj = nsapi.virtual_train.TreinInformatie(**response.json())
#     with open(trein_rit_stations_pkl, 'wb') as file:
#         pickle.dump(obj, file, protocol=-1)
# else:
#     with open(trein_rit_stations_pkl, 'rb') as file:
#         obj = pickle.load(file)

## Other data

In [ ]:
# ARRIVALS 'https://gateway.apiportal.ns.nl/timetable-api/v2/arrivals' https://apiportal.ns.nl/api-details#api=reisinformatie-api&operation=getArrivals&definition=Arrival
# DEPARTURES 'https://gateway.apiportal.ns.nl/timetable-api/v2/departures' https://apiportal.ns.nl/api-details#api=reisinformatie-api&operation=getDepartures
# Arrivals[].plannedTimeZoneOffset
# Arrivals[].plannedDateTime
# Arrivals[].name
# Arrivals[].trainCategory
#   Arrivals[].product.displayName
#   Arrivals[].product.shortCategoryName
# Arrivals[].product.number (string)

In [ ]:
# arrivals_pkl = Path('./ns_results/raw/arrivals.pkl')
# if not arrivals_pkl.exists():
#     response = requests.get('https://gateway.apiportal.ns.nl/timetable-api' + '/v2' + '/arrivals', headers=NS_GET_HEADER,
#         params=nsapi.reisinformatie.ApiV2ArrivalsGetParameters(
#             # uicCode=station_uic_code
#             maxJourneys=100 # default 40
#         )
#     )
#     obj = nsapi.reisinformatie.RepresentationResponseArrivalsPayload(**response.json())
#     with open(arrivals_pkl, 'wb') as file:
#         pickle.dump(obj, file, protocol=-1)
# else:
#     with open(arrivals_pkl, 'rb') as file:
#         obj = pickle.load(file)

In [ ]:
# departures_pkl = Path('./ns_results/raw/departures.pkl')
# if not departures_pkl.exists():
#     response = requests.get('https://gateway.apiportal.ns.nl/timetable-api' + '/v2' + '/departures', headers=NS_GET_HEADER,
#         params=nsapi.reisinformatie.ApiV2DeparturesGetParameters(
#             # uicCode=station_uic_code
#             maxJourneys=100, # default 40
#         )
#     )
#     obj = nsapi.reisinformatie.RepresentationResponseDeparturesPayload(**response.json())
#     with open(departures_pkl, 'wb') as file:
#         pickle.dump(obj, file, protocol=-1)
# else:
#     with open(departures_pkl, 'rb') as file:
#         obj = pickle.load(file)